# -*- coding: utf-8 -*-
# Remaining services (websites, ecommerce, blockchain, more). Same schema as services_data.py.

SERVICES_EXTRA = [
    # ---------------- WEBSITES ----------------
    {
        "cat": "websites", "file": "corporate-website.html", "img": "office",
        "title_key": "services.websites.corporate", "title_en": "Corporate Website",
        "desc": "Polished corporate websites by Amatis that present your company with confidence and convert visitors.",
        "c": {
            "en": {"subtitle": "Polished corporate websites that present your company with confidence.",
                   "p1": "Your website is your digital shopfront. We craft performance-driven corporate sites with clear messaging, strong brand identity and seamless conversion paths — from landing pages to complete multi-page experiences.",
                   "p2": "Built on modern stacks, optimized for speed, SEO and easy content updates, so your team stays in control.",
                   "f1": "Conversion-focused layout & messaging", "f2": "Brand identity & visual design",
                   "f3": "SEO-ready, fast and accessible", "f4": "CMS for easy content updates",
                   "f5": "Analytics, A/B testing & optimization"},
            "de": {"subtitle": "Hochwertige Unternehmenswebsites, die Ihr Unternehmen souverän präsentieren.",
                   "p1": "Ihre Website ist Ihr digitales Schaufenster. Wir entwickeln leistungsstarke Unternehmensseiten mit klarer Botschaft, starker Markenidentität und nahtlosen Konversionspfaden – von Landingpages bis zu mehrseitigen Erlebnissen.",
                   "p2": "Mit modernen Technologien, optimiert für Geschwindigkeit, SEO und einfache Inhalts-Pflege, damit Ihr Team die Kontrolle behält.",
                   "f1": "Konversionsorientiertes Layout & Messaging", "f2": "Markenidentität & visuelles Design",
                   "f3": "SEO-bereit, schnell & barrierefrei", "f4": "CMS für einfache Inhalts-Pflege",
                   "f5": "Analysen, A/B-Tests & Optimierung"},
            "fa": {"subtitle": "وب‌سایت‌های شرکتی حرفه‌ای که شرکت شما را با اعتمادبه‌نفس معرفی می‌کنند.",
                   "p1": "وب‌سایت شما ویترین دیجیتال کسب‌وکارتان است. وب‌سایت‌های شرکتی نتیجه‌محور با پیام مشخص، هویت برند قوی و مسیرهای تبدیل بدون‌وقفه می‌سازیم — از لندینگ‌پیج تا تجربه‌های چندصفحه‌ای کامل.",
                   "p2": "با استک‌های مدرن، بهینه‌شده برای سرعت، سئو و مدیریت آسان محتوا تا تیم شما همیشه کنترل در دست داشته باشد.",
                   "f1": "چیدمان و پیام‌رسانی متمرکز بر تبدیل", "f2": "هویت برند و طراحی بصری",
                   "f3": "آماده سئو، سریع و در دسترس", "f4": "سیستم مدیریت محتوا برای آپدیت آسان",
                   "f5": "آنالیتیکس، تست A/B و بهینه‌سازی"},
            "ar": {"subtitle": "مواقع شركات مصقولة تقدّم شركتك بثقة وتحوّل الزوار إلى عملاء.",
                   "p1": "موقعك هو واجهة نشاطك الرقمية. ننشئ مواقع شركات موجهة للأداء برسالة واضحة وهوية علامة قوية ومسارات تحويل سلسة — من صفحات الهبوط إلى تجارب متعددة الصفحات كاملة.",
                   "p2": "مبنية بتقنيات حديثة ومحسّنة للسرعة وتحسين محركات البحث وسهولة تحديث المحتوى ليبقى الفريق مسيطرًا دائمًا.",
                   "f1": "تصميم ورسالة يركزان على التحويل", "f2": "هوية العلامة والتصميم البصري",
                   "f3": "جاهز لمحركات البحث وسريع وواضح", "f4": "نظام إدارة محتوى سهل التحديث",
                   "f5": "تحليلات واختبار A/B وتحسين مستمر"},
        },
    },
    {
        "cat": "websites", "file": "classifieds-website.html", "img": "market",
        "title_key": "services.websites.classifieds", "title_en": "Classifieds Website",
        "desc": "Classifieds websites by Amatis — powerful search and posting platforms built like the big listing networks.",
        "c": {
            "en": {"subtitle": "Classifieds websites like the big listing platforms — search, post, chat.",
                   "p1": "Launch a listing marketplace for vehicles, real estate, jobs or general classifieds. We engineer searchable, filterable platforms with user accounts, secure posting and messaging built in.",
                   "p2": "Monetize with featured listings, ad placements and premium accounts while keeping moderation and trust features central.",
                   "f1": "Powerful search & category filters", "f2": "User accounts & secure posting",
                   "f3": "Messaging & favorite listings", "f4": "Featured listings & ad placements",
                   "f5": "Moderation, reports & trust tools"},
            "de": {"subtitle": "Kleinanzeigen-Portale wie die großen Listing-Netzwerke – suchen, inserieren, chatten.",
                   "p1": "Starten Sie einen Marktplatz für Fahrzeuge, Immobilien, Jobs oder allgemeine Kleinanzeigen. Wir bauen durchsuchbare, filterbare Plattformen mit Benutzerkonten, sicherem Inserieren und Messaging.",
                   "p2": "Verdienen Sie mit Top-Anzeigen, Werbeplätzen und Premium-Konten – mit Moderation und Vertrauensfeatures im Kern.",
                   "f1": "Leistungsstarke Suche & Kategorie-Filter", "f2": "Benutzerkonten & sicheres Inserieren",
                   "f3": "Messaging & Merkliste", "f4": "Top-Anzeigen & Werbeplätze",
                   "f5": "Moderation, Meldungen & Vertrauenstools"},
            "fa": {"subtitle": "وب‌سایت آگهی مانند پلتفرم‌های بزرگ فهرست — جستجو، انتشار، گفتگو.",
                   "p1": "بازار آگهی برای خودرو، املاک، مشاغل یا آگهی‌های عمومی راه‌اندازی کنید. پلتفرم‌های قابل جستجو و فیلتر با حساب کاربری، انتشار امن و پیام‌رسانی را از پایه مهندسی می‌کنیم.",
                   "p2": "با آگهی ویژه، جایگاه تبلیغاتی و حساب‌های پرمیوم کسب درآمد کنید، در حالی که ابزارهای نظارت و اعتماد همیشه مرکزی مانده‌اند.",
                   "f1": "جستجوی قدرتمند و فیلتر دسته‌ها", "f2": "حساب کاربری و انتشار امن",
                   "f3": "پیام‌رسانی و آگهی‌های نشان‌شده", "f4": "آگهی ویژه و جایگاه‌های تبلیغاتی",
                   "f5": "نظارت، گزارش تخلف و ابزارهای اعتماد"},
            "ar": {"subtitle": "مواقع إعلانات مبوبة كشبكات القوائم الكبيرة — بحث ونشر ومحادثة.",
                   "p1": "أطلق سوق إعلانات للسيارات أو العقارات أو الوظائف أو الإعلانات العامة. نبني منصات قابلة للبحث والتصفية مع حسابات مستخدمين ونشر آمن ومراسلة مدمجة.",
                   "p2": "حقق إيرادات من الإعلانات المميزة والمواضع الإعلانية والحسابات الممتازة مع بقاء الرقابة وأدوات الثقة في الصميم.",
                   "f1": "بحث قوي وفلاتر للفئات", "f2": "حسابات مستخدمين ونشر آمن",
                   "f3": "مراسلة وقوائم مفضلة", "f4": "إعلانات مميزة ومواضع إعلانية",
                   "f5": "إشراف وتبليغ وأدوات ثقة"},
        },
    },
    {
        "cat": "websites", "file": "marketplace-website.html", "img": "shop",
        "title_key": "services.websites.marketplace", "title_en": "Marketplace Website",
        "desc": "Multi-vendor marketplace websites by Amatis — stores, carts, checkout and seller management in one platform.",
        "c": {
            "en": {"subtitle": "Marketplaces with multi-vendor stores and checkout.",
                   "p1": "We build marketplace platforms that let many sellers offer their products under one trusted brand. Vendor dashboards, commission handling, order routing and multi-store checkout are all included.",
                   "p2": "Scale with seller applications, reviews, disputes and payout automation that keeps your marketplace fair and fast.",
                   "f1": "Vendor stores & seller dashboards", "f2": "Commission & payout automation",
                   "f3": "Unified marketplace checkout", "f4": "Reviews, ratings & dispute handling",
                   "f5": "Category management & searchable catalog"},
            "de": {"subtitle": "Multi-Vendor-Marktplätze mit Stores und Checkout.",
                   "p1": "Wir bauen Marktplatz-Plattformen, auf denen viele Verkäufer ihre Produkte unter einer vertrauenswürdigen Marke anbieten. Verkäufer-Dashboards, Provisionsabwicklung, Bestell-Routing und Multi-Store-Checkout sind integriert.",
                   "p2": "Skalieren Sie mit Verkäufer-Applications, Bewertungen, Streitfällen und automatisierten Auszahlungen, die Ihren Marktplatz fair und schnell halten.",
                   "f1": "Verkäufer-Stores & Dashboards", "f2": "Provision & Auszahlungs-Automatisierung",
                   "f3": "Einheitlicher Marktplatz-Checkout", "f4": "Bewertungen, Sterne & Streitfälle",
                   "f5": "Kategorie-Verwaltung & durchsuchbarer Katalog"},
            "fa": {"subtitle": "بازارگاه چندفروشنده با فروشگاه، سبد خرید و تسویه‌حساب یکپارچه.",
                   "p1": "پلتفرم‌های مارکت‌پلیس می‌سازیم که به فروشندگان متعدد اجازه می‌دهد محصولاتشان را زیر یک برند قابل اعتماد ارائه دهند. پنل فروشنده، مدیریت کمیسیون، مسیریابی سفارش و تسویه‌حساب چندفروشگاهی همگی ارائه می‌شود.",
                   "p2": "با فرایند پذیرش فروشنده، نظرات، اختلاف‌ها و اتوماسیون پرداخت به فروشندگان مقیاس‌پذیر رشد کنید.",
                   "f1": "فروشگاه فروشندگان و پنل آن‌ها", "f2": "کمیسیون و اتوماسیون تسویه",
                   "f3": "تسویه‌حساب یکپارچه مارکت‌پلیس", "f4": "نظرات، امتیازها و رسیدگی به اختلاف",
                   "f5": "مدیریت دسته‌ها و کاتالوگ قابل جستجو"},
            "ar": {"subtitle": "أسواق متعددة البائعين مع متاجر وسلة ودفع موحد.",
                   "p1": "نبني منصات الأسواق التي تتيح للعديد من البائعين عرض منتجاتهم تحت علامة واحدة موثوقة. لوحات البائعين ومعالجة العمولات وتوجيه الطلبات ودفع متعدد المتاجر كلها مدمجة.",
                   "p2": "نموّ مع طلبات البائعين والتقييمات والنزاعات وأتمتة المدفوعات ليبقى سوقك عادلًا وسريعًا.",
                   "f1": "متاجر البائعين ولوحات التحكم", "f2": "العمولات وأتمتة المدفوعات",
                   "f3": "دفع موحد للسوق", "f4": "تقييمات ونزاعات وإدارة",
                   "f5": "إدارة الفئات وكتالوج قابل للبحث"},
        },
    },
    {
        "cat": "websites", "file": "online-store.html", "img": "store",
        "title_key": "services.websites.store", "title_en": "Online Store",
        "desc": "Fast online stores by Amatis — catalogs, seamless payments, shipping and full admin control.",
        "c": {
            "en": {"subtitle": "Fast online stores with catalogs, payments and shipping.",
                   "p1": "Turn your products into an online store that sells around the clock. We build fast, reliable shops with smart catalogs, smooth checkout, secure payments and shipping integration.",
                   "p2": "You stay in control with an admin panel for products, orders, discounts, customers and marketing tools.",
                   "f1": "Smart product catalogs & search", "f2": "Seamless, secure checkout",
                   "f3": "Local & international payment gateways", "f4": "Shipping & order management",
                   "f5": "Admin panel, discounts & marketing"},
            "de": {"subtitle": "Schnelle Online-Stores mit Katalogen, Zahlungen und Versand.",
                   "p1": "Verwandeln Sie Ihre Produkte in einen Online-Shop, der rund um die Uhr verkauft. Wir bauen schnelle, zuverlässige Shops mit intelligenten Katalogen, reibungslosem Checkout, sicheren Zahlungen und Versand-Integration.",
                   "p2": "Sie bleiben mit einem Admin-Panel für Produkte, Bestellungen, Rabatte, Kunden und Marketing im Griff.",
                   "f1": "Smartes Produktmanagement & Suche", "f2": "Reibungsloser, sicherer Checkout",
                   "f3": "Lokale & internationale Zahlungsanbieter", "f4": "Versand & Bestellverwaltung",
                   "f5": "Admin-Panel, Rabatte & Marketing"},
            "fa": {"subtitle": "فروشگاه اینترنتی سریع با کاتالوگ، پرداخت و ارسال.",
                   "p1": "محصولات خود را به فروشگاه آنلاینی تبدیل کنید که ۲۴ ساعته می‌فروشد. فروشگاه‌هایی سریع و مطمئن با کاتالوگ هوشمند، تسویه‌حساب روان، پرداخت امن و یکپارچه‌سازی حمل‌ونقل می‌سازیم.",
                   "p2": "با پنل مدیریت محصولات، سفارش‌ها، تخفیف‌ها، مشتریان و ابزارهای بازاریابی، همیشه کنترل در دست شماست.",
                   "f1": "کاتالوگ هوشمند و جستجوی محصول", "f2": "تسویه‌حساب امن و روان",
                   "f3": "درگاه‌های پرداخت داخلی و بین‌المللی", "f4": "مدیریت ارسال و سفارش",
                   "f5": "پنل مدیریت، تخفیف و بازاریابی"},
            "ar": {"subtitle": "متاجر إلكترونية سريعة مع كتالوجات ومدفوعات وشحن.",
                   "p1": "حوّل منتجاتك إلى متجر إلكتروني يبيع على مدار الساعة. نبني متاجر سريعة وموثوقة مع كتالوجات ذكية ودفع سلس ومدفوعات آمنة وتكامل للشحن.",
                   "p2": "تبقى مسيطرًا عبر لوحة إدارة للمنتجات والطلبات والخصومات والعملاء وأدوات التسويق.",
                   "f1": "كتالوجات ذكية وبحث عن المنتجات", "f2": "دفع سلس وآمن",
                   "f3": "بوابات دفع محلية ودولية", "f4": "إدارة الشحن والطلبات",
                   "f5": "لوحة إدارة وخصومات وتسويق"},
        },
    },
    {
        "cat": "websites", "file": "restaurant-website.html", "img": "restaurant",
        "title_key": "services.websites.restaurant", "title_en": "Restaurant Website",
        "desc": "Restaurant websites by Amatis — beautiful menus, table reservation and online ordering.",
        "c": {
            "en": {"subtitle": "Restaurant sites with menus, table reservation and online ordering.",
                   "p1": "Bring your restaurant online with an appetizing website. Menu showcase, table reservations, online ordering and kitchen integrations all work together to fill every seat.",
                   "p2": "Delight visitors with photo galleries, chef stories and social proof, and keep regulars coming back with offers and loyalty.",
                   "f1": "Menu showcase & dish galleries", "f2": "Online table reservations",
                   "f3": "Online ordering & payments", "f4": "Location, hours & Google Maps",
                   "f5": "Offers, loyalty & review widgets"},
            "de": {"subtitle": "Restaurant-Websites mit Menüs, Tischreservierung und Online-Bestellung.",
                   "p1": "Bringen Sie Ihr Restaurant mit einer appetitanregenden Website online. Menü-Präsentation, Tischreservierung, Online-Bestellung und Küchen-Integrationen füllen jeden Platz.",
                   "p2": "Begeistern Sie Besucher mit Fotogalerien, Koch-Geschichten und Social Proof – und binden Sie Stammgäste mit Angeboten und Treueprogrammen.",
                   "f1": "Menü-Präsentation & Gericht-Galerien", "f2": "Online-Tischreservierung",
                   "f3": "Online-Bestellung & Zahlung", "f4": "Standort, Öffnungszeiten & Karte",
                   "f5": "Angebote, Treue & Bewertungs-Widgets"},
            "fa": {"subtitle": "وب‌سایت رستوران با منو، رزرو میز و سفارش آنلاین.",
                   "p1": "رستوران خود را با وب‌سایتی اشتهاآور آنلاین کنید. نمایش منو، رزرو میز، سفارش آنلاین و یکپارچه‌سازی آشپزخانه با هم کار می‌کنند تا هر صندلی پر شود.",
                   "p2": "بازدیدکنندگان را با گالری عکس، داستان سرآشپز و اعتماد اجتماعی جذب کنید و با پیشنهادها و وفاداری، مشتریان ثابت را برگردانید.",
                   "f1": "نمایش منو و گالری غذاها", "f2": "رزرو آنلاین میز",
                   "f3": "سفارش آنلاین و پرداخت", "f4": "موقعیت، ساعات کاری و نقشه",
                   "f5": "پیشنهادها، وفاداری و ویجت نظرات"},
            "ar": {"subtitle": "مواقع مطاعم مع قوائم طعام وحجز طاولات وطلب إلكتروني.",
                   "p1": "قدّم مطعمك عبر الإنترنت بموقع شهيّ. عرض القائمة وحجز الطاولات والطلب الإلكتروني وتكامل المطبخ تعمل معًا لملء كل مقعد.",
                   "p2": "أسحر الزوار بمعارض الصور وقصص الشيف والدليل الاجتماعي، وأعد الأوفياء بعروض وبرامج ولاء.",
                   "f1": "عرض القائمة ومعارض الأطباق", "f2": "حجز طاولات عبر الإنترنت",
                   "f3": "طلب إلكتروني ومدفوعات", "f4": "الموقع وساعات العمل وخرائط Google",
                   "f5": "عروض وولاء وأدوات تقييم"},
        },
    },
    {
        "cat": "websites", "file": "news-website.html", "img": "newspaper",
        "title_key": "services.websites.news", "title_en": "News Website",
        "desc": "News and media websites by Amatis — editorial workflows, fast delivery and audience growth.",
        "c": {
            "en": {"subtitle": "News sites with editorial workflows and fast delivery.",
                   "p1": "We build modern news and media platforms with intuitive editorial workflows, lightning-fast article delivery and engaging layouts for desktop, tablet and mobile.",
                   "p2": "Monetize with subscriptions, ads and sponsors while empowering your team with analytics and content scheduling.",
                   "f1": "Editorial workflow & publishing tools", "f2": "Fast, SEO-optimized articles",
                   "f3": "Break categories, tags & search",
                   "f4": "Subscriptions, ads & sponsors", "f5": "Analytics & content scheduling"},
            "de": {"subtitle": "Nachrichten-Websites mit Redaktions-Workflows und schneller Auslieferung.",
                   "p1": "Wir bauen moderne Nachrichten- und Medienplattformen mit intuitiven Redaktionsprozessen, blitzschneller Artikelauslieferung und ansprechenden Layouts für Desktop, Tablet und Mobilgeräte.",
                   "p2": "Verdienen Sie mit Abonnements, Anzeigen und Sponsorings und stärken Sie Ihr Team mit Analysen und Content-Planung.",
                   "f1": "Redaktions-Workflow & Publishing-Tools", "f2": "Schnelle, SEO-optimierte Artikel",
                   "f3": "Kategorien, Tags & Suche",
                   "f4": "Abos, Anzeigen & Sponsoring", "f5": "Analysen & Content-Planung"},
            "fa": {"subtitle": "وب‌سایت خبری با فرایندهای تحریریه و انتشار سریع.",
                   "p1": "پلتفرم‌های خبری و رسانه‌ای مدرن با فرایندهای تحریریه روان، انتشار فوق‌العاده سریع مقاله و چیدمان جذاب برای دسکتاپ، تبلت و موبایل می‌سازیم.",
                   "p2": "با اشتراک، تبلیغات و اسپانسر کسب درآمد کنید و تیم خود را با آنالیتیکس و زمان‌بندی محتوا قدرتمند کنید.",
                   "f1": "فرایند تحریریه و ابزارهای انتشار", "f2": "مقاله‌های سریع و بهینه برای سئو",
                   "f3": "دسته‌بندی، برچسب و جستجو",
                   "f4": "اشتراک، تبلیغات و اسپانسر", "f5": "آنالیتیکس و زمان‌بندی محتوا"},
            "ar": {"subtitle": "مواقع أخبار مع سير عمل تحريري وتوصيل سريع.",
                   "p1": "نبني منصات أخبار ووسائط حديثة بسير عمل تحريري بديهي وتوصيل سريع جدًا للمقالات وتصاميم جذابة للحاسوب واللوحي والجوال.",
                   "p2": "حقق الإيرادات من الاشتراكات والإعلانات والرعاية مع تمكين فريقك بالتحليلات وجدولة المحتوى.",
                   "f1": "سير عمل تحريري وأدوات نشر", "f2": "مقالات سريعة ومحسّنة لمحركات البحث",
                   "f3": "تصنيفات ووسوم وبحث",
                   "f4": "اشتراكات وإعلانات ورعاية", "f5": "تحليلات وجدولة محتوى"},
        },
    },
    {
        "cat": "websites", "file": "medical-website.html", "img": "hospital",
        "title_key": "services.websites.medical", "title_en": "Medical Website",
        "desc": "Medical and clinic websites by Amatis — online booking, patient portals and trust-building design.",
        "c": {
            "en": {"subtitle": "Clinic sites with online booking and patient portals.",
                   "p1": "We design trustworthy websites for clinics, doctors and health centers. Online appointment booking, patient information, service overviews and privacy-first practices build confidence from the first visit.",
                   "p2": "Inform and reassure with team profiles, articles and FAQs, while compliant forms and secure data handling keep patient trust intact.",
                   "f1": "Online appointment booking", "f2": "Service, team & facility overviews",
                   "f3": "Patient education articles & FAQs", "f4": "Privacy-first, secure data handling",
                   "f5": "Responsive, accessible design"},
            "de": {"subtitle": "Klinik-Websites mit Online-Buchung und Patientenportalen.",
                   "p1": "Wir gestalten vertrauenswürdige Websites für Kliniken, Ärzte und Gesundheitszentren. Online-Terminbuchung, Patienteninformationen, Leistungsübersichten und datenschutz-erste Praktiken schaffen ab dem ersten Besuch Vertrauen.",
                   "p2": "Informieren und beruhigen Sie mit Team-Profilen, Artikeln und FAQs, während konforme Formulare und sichere Datenverarbeitung das Patientenvertrauen wahren.",
                   "f1": "Online-Terminbuchung", "f2": "Leistungs-, Team- & Einrichtungsübersichten",
                   "f3": "Patienten-Artikel & FAQs", "f4": "Datenschutz-orientierte, sichere Verarbeitung",
                   "f5": "Responsive, barrierefreies Design"},
            "fa": {"subtitle": "وب‌سایت درمانگاه با رزرو آنلاین و پرتال بیماران.",
                   "p1": "برای کلینیک‌ها، پزشکان و مراکز درمانی وب‌سایت‌هایی قابل اعتماد طراحی می‌کنیم. رزرو آنلاین نوبت، اطلاعات بیماران، معرفی خدمات و رعایت حریم خصوصی از اولین بازدید اعتماد ایجاد می‌کنند.",
                   "p2": "با معرفی تیم، مقاله و سوالات متداول اطلاع‌رسانی و اطمینان‌بخشی کنید، در حالی که فرم‌های مطابق قانون و پردازش امن داده، اعتماد بیمار را حفظ می‌کنند.",
                   "f1": "رزرو آنلاین نوبت", "f2": "معرفی خدمات، تیم و امکانات",
                   "f3": "مقالات آموزشی و سوالات متداول", "f4": "پردازش امن و حریم‌خصوصی‌محور داده",
                   "f5": "طراحی واکنش‌گرا و در دسترس"},
            "ar": {"subtitle": "مواقع العيادات مع حجز إلكتروني وبوابات للمرضى.",
                   "p1": "نصمم مواقع موثوقة للعيادات والأطباء ومراكز الصحة. الحجز الإلكتروني ومعلومات المرضى واستعراض الخدمات والممارسات القائمة على الخصوصية تبني الثقة من أول زيارة.",
                   "p2": "أبلغ وطمئن عبر التعريف بالفريق والمقالات والأسئلة الشائعة، بينما تحافظ النماذج المتوافقة والمعالجة الآمنة للبيانات على ثقة المرضى.",
                   "f1": "حجز مواعيد إلكتروني", "f2": "استعراض الخدمات والفريق والمنشآت",
                   "f3": "مقالات توعوية وأسئلة شائعة", "f4": "معالجة بيانات آمنة تحترم الخصوصية",
                   "f5": "تصميم سريع الاستجابة وواضح"},
        },
    },
    {
        "cat": "websites", "file": "tourism-website.html", "img": "beach",
        "title_key": "services.websites.tourism", "title_en": "Tourism Website",
        "desc": "Travel and tourism websites by Amatis — tours, hotels and trip booking that inspire and convert.",
        "c": {
            "en": {"subtitle": "Travel and tourism websites with tours, hotels and trip booking.",
                   "p1": "Inspire travelers and turn clicks into bookings. We build beautiful tourism websites with immersive destination content, tour catalogs and seamless booking flows.",
                   "p2": "Highlight packages and special deals, and let visitors plan trips with itineraries, galleries and trust-building reviews.",
                   "f1": "Destination & tour showcase", "f2": "Tour and hotel booking flows",
                   "f3": "Itineraries, galleries & maps", "f4": "Multi-language content",
                   "f5": "Reviews, offers & trust signals"},
            "de": {"subtitle": "Reise- und Tourismus-Websites mit Touren, Hotels und Buchung.",
                   "p1": "Inspirieren Sie Reisende und verwandeln Sie Klicks in Buchungen. Wir bauen schöne Tourismus-Websites mit immersiven Ziel-Inhalten, Tour-Katalogen und nahtlosen Buchungsabläufen.",
                   "p2": "Heben Sie Pakete und Angebote hervor und lassen Sie Besucher Reisen mit Routen, Galerien und vertrauensbildenden Bewertungen planen.",
                   "f1": "Ziele & Touren anschaulich präsentiert", "f2": "Buchungsabläufe für Touren & Hotels",
                   "f3": "Reiserouten, Galerien & Karten", "f4": "Mehrsprachige Inhalte",
                   "f5": "Bewertungen, Angebote & Vertrauenssignale"},
            "fa": {"subtitle": "وب‌سایت گردشگری و سفر با تور، هتل و رزرو سفر الهام‌بخش.",
                   "p1": "مسافران را الهام بگیرید و کلیک را به رزرو تبدیل کنید. وب‌سایت‌های گردشگری زیبا با محتوای جذاب مقصد، کاتالوگ تور و فرایند رزرو روان می‌سازیم.",
                   "p2": "پکیج‌ها و پیشنهادهای ویژه را برجسته کنید و به بازدیدکنندگان اجازه دهید با سفرنامه، گالری و نظرات اعتمادآفرین سفرشان را برنامه‌ریزی کنند.",
                   "f1": "معرفی مقصد و تورها", "f2": "فرایند رزرو تور و هتل",
                   "f3": "سفرنامه، گالری و نقشه", "f4": "محتوای چندزبانه",
                   "f5": "نظرات، پیشنهادها و نشانه‌های اعتماد"},
            "ar": {"subtitle": "مواقع السياحة والسفر مع جولات وفنادق وحجوزات.",
                   "p1": "ألهم المسافرين وحوّل النقرات إلى حجوزات. نبني مواقع سياحية جميلة بمحتوى جذاب للوجهات وكتالوجات الجولات ومسارات حجز سلسة.",
                   "p2": "أبرز الباقات والعروض الخاصة، ودع الزوار يخططون رحلاتهم بمسارات ومعارض وتقييمات تبني الثقة.",
                   "f1": "عرض الوجهات والجولات", "f2": "مسارات حجز الجولات والفنادق",
                   "f3": "مسارات رحلات ومعارض وخرائط", "f4": "محتوى متعدد اللغات",
                   "f5": "تقييمات وعروض وإشارات ثقة"},
        },
    },
    {
        "cat": "websites", "file": "book-reader-website.html", "img": "library",
        "title_key": "services.websites.reader", "title_en": "Book Reader Website",
        "desc": "Book reader websites by Amatis — sell and stream ebooks and audiobooks with a beautiful reading experience.",
        "c": {
            "en": {"subtitle": "Book reader websites for selling and streaming ebooks and audiobooks.",
                   "p1": "Launch a reading platform for your publishing house or library. A beautiful catalog, secure e-book purchases, subscriptions and an in-browser reader make every title easy to enjoy.",
                   "p2": "Include audiobook streaming, reviews, wishlists and reader accounts to build a loyal community around your books.",
                   "f1": "E-book store & secure purchases", "f2": "In-browser reader experience",
                   "f3": "Audiobook streaming & player", "f4": "Subscriptions & memberships",
                   "f5": "Reviews, wishlists & reader accounts"},
            "de": {"subtitle": "Lese-Websites für den Verkauf und Streaming von E-Books und Hörbüchern.",
                   "p1": "Starten Sie eine Leselplatform für Ihren Verlag oder Ihre Bibliothek. Ein schöner Katalog, sichere E-Book-Käufe, Abonnements und ein In-Browser-Reader machen jedes Buch einfach zugänglich.",
                   "p2": "Mit Hörbuch-Streaming, Bewertungen, Wunschlisten und Leserkonten bauen Sie eine loyale Community rund um Ihre Bücher.",
                   "f1": "E-Book-Store & sichere Käufe", "f2": "In-Browser-Reader",
                   "f3": "Hörbuch-Streaming & Player", "f4": "Abonnements & Mitgliedschaften",
                   "f5": "Bewertungen, Wunschlisten & Leserkonten"},
            "fa": {"subtitle": "وب‌سایت کتاب‌خوان برای فروش و استریم کتاب الکترونیک و صوتی.",
                   "p1": "پلتفرم مطالعه برای ناشر یا کتابخانه خود راه‌اندازی کنید. کاتالوگ زیبا، خرید امن کتاب الکترونیک، اشتراک و کتاب‌خوان درون مرورگر، هر کتاب را آسان در دسترس می‌کند.",
                   "p2": "با استریم کتاب صوتی، نظرات، علاقه‌مندی و حساب کاربری، جامعه‌ای وفادار حول کتاب‌هایتان بسازید.",
                   "f1": "فروشگاه کتاب الکترونیک و خرید امن", "f2": "تجربه مطالعه درون مرورگر",
                   "f3": "استریم کتاب صوتی و پخش‌کننده", "f4": "اشتراک و عضویت",
                   "f5": "نظرات، علاقه‌مندی و حساب کاربری"},
            "ar": {"subtitle": "مواقع قراءة لبيع وبث الكتب الإلكترونية والصوتية.",
                   "p1": "أطلق منصة قراءة لدار نشرك أو مكتبتك. كتالوج جميل وشراء آمن للكتب الإلكترونية واشتراكات وقارئ داخل المتصفح تجعل كل كتاب سهل المتعة.",
                   "p2": "أضف بث الكتب الصوتية والتقييمات وقوائم الأمنيات وحسابات القرّاء لبناء مجتمع وفيّ حول كتبك.",
                   "f1": "متجر كتب إلكترونية وشراء آمن", "f2": "تجربة قراءة داخل المتصفح",
                   "f3": "بث الكتب الصوتية ومشغل", "f4": "اشتراكات وعضويات",
                   "f5": "تقييمات وقوائم أمنيات وحسابات قرّاء"},
        },
    },
    {
        "cat": "websites", "file": "wordpress.html", "img": "laptop",
        "title_key": "services.websites.wordpress", "title_en": "WordPress Website",
        "desc": "WordPress websites by Amatis — custom themes, plugins and builds tuned for speed and SEO.",
        "c": {
            "en": {"subtitle": "WordPress sites built and tuned for speed, SEO and easy editing.",
                   "p1": "WordPress gives your team total control over content. We build custom themes, required plugins and optimized setups — fast, secure and easy for authors to update every day.",
                   "p2": "From blogs to full company sites and online stores, we tailor WordPress to your business with professional design and maintenance.",
                   "f1": "Custom themes & page builder setup", "f2": "Speed, Core Web Vitals & SEO tuning",
                   "f3": "Security, backups & updates", "f4": "Easy editing for non-technical teams",
                   "f5": "Ongoing support and care plans"},
            "de": {"subtitle": "WordPress-Websites, optimiert für Geschwindigkeit, SEO und einfache Pflege.",
                   "p1": "WordPress gibt Ihrem Team volle Kontrolle über Inhalte. Wir bauen Custom-Themes, passende Plugins und optimierte Setups – schnell, sicher und für Autoren täglich leicht zu aktualisieren.",
                   "p2": "Von Blogs über komplette Firmenseiten bis zu Online-Shops passen wir WordPress mit professionellem Design und Pflege an Ihr Geschäft an.",
                   "f1": "Custom-Themes & Page-Builder-Setup", "f2": "Speed, Core Web Vitals & SEO",
                   "f3": "Sicherheit, Backups & Updates", "f4": "Leichtes Bearbeiten ohne IT-Wissen",
                   "f5": "Laufender Support & Care-Pläne"},
            "fa": {"subtitle": "وب‌سایت وردپرسی بهینه‌شده برای سرعت، سئو و مدیریت آسان.",
                   "p1": "وردپرس کنترل کامل محتوا را به تیم شما می‌دهد. قالب اختصاصی، افزونه‌های لازم و تنظیمات بهینه می‌سازیم — سریع، امن و به‌سادگی قابل‌آپدیت توسط تیم نویسندگان هر روز.",
                   "p2": "از وبلاگ تا وب‌سایت کامل شرکتی و فروشگاه آنلاین، وردپرس را با طراحی حرفه‌ای و پشتیبانی با کسب‌وکار شما هماهنگ می‌کنیم.",
                   "f1": "قالب اختصاصی و تنظیم پیج‌بیلدر", "f2": "سرعت، Core Web Vitals و سئو",
                   "f3": "امنیت، بکاپ و به‌روزرسانی", "f4": "مدیریت آسان برای تیم غیرفنی",
                   "f5": "پشتیبانی مستمر و برنامه پشتیبانی"},
            "ar": {"subtitle": "مواقع ووردبريس معدّلة للسرعة وتحسين محركات البحث وسهولة التحرير.",
                   "p1": "يمنح ووردبريس فريقك سيطرة كاملة على المحتوى. نبني قوالب مخصصة وإضافات مطلوبة وتهيئة محسّنة — سريعة وآمنة وسهلة التحديث يوميًا للمحررين.",
                   "p2": "من المدونات إلى مواقع الشركات الكاملة والمتاجر الإلكترونية، نكيّف ووردبريس مع عملك بتصميم احترافي وصيانة مستمرة.",
                   "f1": "قوالب مخصصة وإعداد منشئ الصفحات", "f2": "سرعة وCore Web Vitals وSEO",
                   "f3": "أمان ونسخ احتياطي وتحديثات", "f4": "تحرير سهل للفرق غير التقنية",
                   "f5": "دعم مستمر وخطط صيانة"},
        },
    },
    # ---------------- E-COMMERCE ----------------
    {
        "cat": "ecommerce", "file": "subscription-store.html", "img": "business",
        "title_key": "services.ecommerce.subscription", "title_en": "Subscription Store",
        "desc": "Subscription stores by Amatis — memberships, recurring billing, boxes and growing recurring revenue.",
        "c": {
            "en": {"subtitle": "Stores for memberships and recurring revenue.",
                   "p1": "Turn one-time buyers into a predictable revenue stream. We build subscription e-commerce with plans, recurring billing, member portals and automated renewals.",
                   "p2": "Support boxes, memberships, digital goods and cancellations with metrics that show exactly how your business is growing.",
                   "f1": "Plans, tiers & recurring billing", "f2": "Member portal & account management",
                   "f3": "Payment gateway retry automation", "f4": "Subscription boxes & digital goods",
                   "f5": "Churn analytics & growth reports"},
            "de": {"subtitle": "Stores für Mitgliedschaften und wiederkehrende Einnahmen.",
                   "p1": "Verwandeln Sie Einmalkäufer in eine planbare Einnahmequelle. Wir bauen Abo-E-Commerce mit Tarifen, wiederkehrender Abrechnung, Mitgliederportalen und automatischer Verlängerung.",
                   "p2": "Unterstützen Sie Boxen, Mitgliedschaften, digitale Güter und Kündigungen – mit Metriken, die Ihre Geschäftsentwicklung genau zeigen.",
                   "f1": "Tarife & wiederkehrende Abrechnung", "f2": "Mitgliederportal & Kontenverwaltung",
                   "f3": "Zahlungs-Retry-Automatisierung", "f4": "Abo-Boxen & digitale Güter",
                   "f5": "Churn-Analysen & Wachstumsberichte"},
            "fa": {"subtitle": "فروشگاه اشتراکی برای عضویت و درآمد تکرارشونده.",
                   "p1": "خریداران یک‌باره را به جریان درآمدی قابل‌پیش‌بینی تبدیل کنید. تجارت الکترونیک اشتراکی با پلن‌ها، پرداخت دوره‌ای، پرتال عضو و تمدید خودکار می‌سازیم.",
                   "p2": "باکس اشتراک، عضویت، کالای دیجیتال و لغو اشتراک را با معیارهایی پشتیبانی می‌کنیم که دقیقاً رشد کسب‌وکار را نشان می‌دهند.",
                   "f1": "پلن‌ها، سطوح و پرداخت دوره‌ای", "f2": "پرتال عضو و مدیریت حساب",
                   "f3": "اتوماسیون تلاش مجدد پرداخت", "f4": "باکس اشتراک و کالای دیجیتال",
                   "f5": "آنالیز ریزش و گزارش رشد"},
            "ar": {"subtitle": "متاجر اشتراك للعضوية والإيرادات المتكررة.",
                   "p1": "حوّل المشترين لمرة واحدة إلى مصدر إيرادات يمكن التنبؤ به. نبني تجارة إلكترونية بالاشتراك مع خطط ومدفوعات متكررة وبوابات عضو وتجديد تلقائي.",
                   "p2": "نوفر دعمًا للصناديق والعضويات والمنتجات الرقمية والإلغاءات مع مقاييس تُظهر بدقة نمو أعمالك.",
                   "f1": "خطط ومستويات ودفع متكرر", "f2": "بوابة العضو وإدارة الحساب",
                   "f3": "أتمتة إعادة محاولة الدفع", "f4": "صناديق اشتراك ومنتجات رقمية",
                   "f5": "تحليلات تراجع العملاء وتقارير النمو"},
        },
    },
    {
        "cat": "ecommerce", "file": "shopify-store.html", "img": "retail",
        "title_key": "services.ecommerce.shopify", "title_en": "Shopify Store",
        "desc": "Shopify stores by Amatis — configured and customized to your brand for sales and scale.",
        "c": {
            "en": {"subtitle": "Shopify stores configured and customized to your brand.",
                   "p1": "Launch fast with Shopify's proven infrastructure, tailored to your brand. We configure themes, apps and payments to create a store that looks custom and runs perfectly.",
                   "p2": "Optimize for conversions and scale with apps for marketing, fulfillment and analytics — completely managed by our team.",
                   "f1": "Theme customization & brand design", "f2": "App & plugin configuration",
                   "f3": "Payment & shipping setup", "f4": "Conversion & speed optimization",
                   "f5": "Ongoing store management"},
            "de": {"subtitle": "Shopify-Stores, konfiguriert und auf Ihre Marke zugeschnitten.",
                   "p1": "Starten Sie schnell mit der bewährten Shopify-Infrastruktur, auf Ihre Marke zugeschnitten. Wir konfigurieren Themes, Apps und Zahlungen für einen Store, der individuell aussieht und perfekt läuft.",
                   "p2": "Optimieren Sie Konversion und Skalierung mit Apps für Marketing, Fulfillment und Analysen – komplett von unserem Team verwaltet.",
                   "f1": "Theme-Anpassung & Brand-Design", "f2": "App- & Plugin-Konfiguration",
                   "f3": "Zahlungen & Versand-Setup", "f4": "Konversions- & Geschwindigkeits-Optimierung",
                   "f5": "Laufende Store-Verwaltung"},
            "fa": {"subtitle": "فروشگاه شاپیفای متناسب با برند شما.",
                   "p1": "با زیرساخت اثبات‌شده شاپیفای و مطابق برند خود سریع شروع کنید. تم، اپ و پرداخت را طوری پیکربندی می‌کنیم که فروشگاهی اختصاصی و بی‌نقص بسازیم.",
                   "p2": "با اپ‌های بازاریابی، ارسال و آنالیتیکس برای تبدیل و مقیاس‌پذیری بهینه می‌کنیم — کاملاً مدیریت‌شده توسط تیم ما.",
                   "f1": "سفارشی‌سازی قالب و طراحی برند", "f2": "پیکربندی اپ و افزونه",
                   "f3": "تنظیم پرداخت و ارسال", "f4": "بهینه‌سازی نرخ تبدیل و سرعت",
                   "f5": "مدیریت مستمر فروشگاه"},
            "ar": {"subtitle": "متاجر Shopify مُعدّلة ومخصصة لعلامتك التجارية.",
                   "p1": "انطلق بسرعة ببنية Shopify المجرّبة، مصممة لعلامتك. نشكّل القوالب والتطبيقات والمدفوعات لإنشاء متجر يبدو مخصصًا ويعمل بشكل ممتاز.",
                   "p2": "حسّن التحويلات ونمّو بالتطبيقات للتسويق والشحن والتحليلات — بإدارة كاملة من فريقنا.",
                   "f1": "تخصيص القوالب وتصميم العلامة", "f2": "إعداد التطبيقات والإضافات",
                   "f3": "إعداد الدفع والشحن", "f4": "تحسين التحويل والسرعة",
                   "f5": "إدارة متجر مستمرة"},
        },
    },
    # ---------------- BLOCKCHAIN & CRYPTO ----------------
    {
        "cat": "blockchain", "file": "crypto-exchange.html", "img": "bitcoin",
        "title_key": "services.blockchain.cex", "title_en": "Crypto Exchange",
        "desc": "Centralized cryptocurrency exchanges by Amatis — order books, KYC, custody and liquidity.",
        "c": {
            "en": {"subtitle": "Centralized exchanges with order books and KYC.",
                   "p1": "We build secure centralized exchanges (CEX) with matching engines, order books, wallets and full KYC/AML flows. Spot trading, margin and futures modules scale with your user base.",
                   "p2": "Focus on your market while we handle the engineering — from cold wallet custody and risk controls to dashboards and reporting.",
                   "f1": "Matching engine & order book", "f2": "Wallets & cold storage custody",
                   "f3": "KYC/AML identity verification", "f4": "Spot, margin & futures trading",
                   "f5": "Risk, admin & reporting dashboards"},
            "de": {"subtitle": "Zentralisierte Börsen mit Orderbuch und KYC.",
                   "p1": "Wir bauen sichere zentralisierte Börsen (CEX) mit Matching-Engine, Orderbüchern, Wallets und vollständigen KYC/AML-Abläufen. Spot-, Margin- und Futures-Module skalieren mit Ihrer Nutzerbasis.",
                   "p2": "Konzentrieren Sie sich auf Ihren Markt – für die Technik sorgen wir: von Cold-Wallet-Custody und Risikokontrollen bis zu Dashboards und Reporting.",
                   "f1": "Matching-Engine & Orderbuch", "f2": "Wallets & Cold-Storage-Verwahrung",
                   "f3": "KYC/AML-Identitätsprüfung", "f4": "Spot-, Margin- & Futures-Handel",
                   "f5": "Risiko-, Admin- & Reporting-Dashboards"},
            "fa": {"subtitle": "صرافی متمرکز با دفتر سفارش و احراز هویت.",
                   "p1": "صرافی‌های متمرکز (CEX) امن با موتور تطبیق، دفتر سفارش، کیف پول و فرایند کامل KYC/AML می‌سازیم. ماژول‌های معاملات اسپات، مارجین و فیوچرز متناسب با رشد کاربران مقیاس می‌شوند.",
                   "p2": "تمرکز روی بازار خودتان را بسپارید؛ مهندسی با ماست — از نگهداری کیف پول سرد و کنترل ریسک تا داشبوردها و گزارش‌ها.",
                   "f1": "موتور تطبیق و دفتر سفارش", "f2": "کیف پول و نگهداری در انبار سرد",
                   "f3": "احراز هویت KYC/AML", "f4": "معاملات اسپات، مارجین و فیوچرز",
                   "f5": "داشبورد ریسک، مدیریت و گزارش"},
            "ar": {"subtitle": "بورصات مركزية مع دفتر أوامر والتحقق من الهوية KYC.",
                   "p1": "نبني بورصات مركزية آمنة (CEX) بمحركات مطابقة ودفاتر أوامر ومحافظ وتدفقات KYC/AML كاملة. وحدات التداول الفوري والهامش والعقود الآجلة تتوسع مع قاعدة مستخدميك.",
                   "p2": "ركّز على سوقك ودَعنا نتولى الهندسة — من حفظ المحافظ الباردة وضوابط المخاطر إلى لوحات التحكم والتقارير.",
                   "f1": "محرك المطابقة ودفتر الأوامر", "f2": "محافظ وحفظ في التخزين البارد",
                   "f3": "التحقق من الهوية KYC/AML", "f4": "تداول فوري وهامشى وعقود آجلة",
                   "f5": "لوحات مخاطر وإدارة وتقارير"},
        },
    },
    {
        "cat": "blockchain", "file": "dex.html", "img": "cryptocurrency",
        "title_key": "services.blockchain.dex", "title_en": "Decentralized Exchange (DEX)",
        "desc": "Decentralized exchanges by Amatis — on-chain swaps, liquidity pools and self-custody trading.",
        "c": {
            "en": {"subtitle": "Decentralized exchanges with on-chain swaps.",
                   "p1": "We build decentralized exchanges (DEX) where users trade from their own wallets. Automated market makers, liquidity pools, staking and on-chain order flows are engineered for safety and transparency.",
                   "p2": "Smart contracts are audited and optimized for gas efficiency, keeping fees low and trust high.",
                   "f1": "Automated Market Maker (AMM)", "f2": "Liquidity pools & farming",
                   "f3": "Non-custodial wallet trading", "f4": "Audited, gas-optimized contracts",
                   "f5": "Staking, bridges & analytics"},
            "de": {"subtitle": "Dezentrale Börsen mit On-Chain-Swaps.",
                   "p1": "Wir entwickeln dezentrale Börsen (DEX), bei denen Nutzer aus ihren eigenen Wallets handeln. Automated Market Maker, Liquiditätspools, Staking und On-Chain-Auftragsflüsse sind für Sicherheit und Transparenz gebaut.",
                   "p2": "Smart Contracts werden auditiert und gas-optimiert entwickelt – für niedrige Gebühren und hohes Vertrauen.",
                   "f1": "Automated Market Maker (AMM)", "f2": "Liquiditätspools & Farming",
                   "f3": "Non-Custodial-Wallet-Handel", "f4": "Auditierte, gas-optimierte Contracts",
                   "f5": "Staking, Bridges & Analysen"},
            "fa": {"subtitle": "صرافی غیرمتمرکز با سواپ آن‌چین.",
                   "p1": "صرافی‌های غیرمتمرکز (DEX) می‌سازیم که کاربران از کیف پول خودشان معامله می‌کنند. مارکت‌میکر خودکار، استخر نقدینگی، استیکینگ و جریان سفارش آن‌چین برای امنیت و شفافیت مهندسی شده‌اند.",
                   "p2": "قراردادهای هوشمند حسابرسی و بهینه‌شده برای گس هستند تا هزینه کم و اعتماد بالا بماند.",
                   "f1": "مارکت‌میکر خودکار (AMM)", "f2": "استخر نقدینگی و فارمینگ",
                   "f3": "معامله غیردوری با کیف پول شخصی", "f4": "قراردادهای حسابرسی‌شده و بهینه",
                   "f5": "استیکینگ، بریج و آنالیتیکس"},
            "ar": {"subtitle": "بورصات لا مركزية مع مقايضات على السلسلة.",
                   "p1": "نبني بورصات لا مركزية (DEX) يتداول منها المستخدمون عبر محافظهم الخاصة. صانعو السوق الآليون ومجمعات السيولة والتخزين وتدفقات الأوامر على السلسلة مُهيأة للأمان والشفافية.",
                   "p2": "يتم مراجعة العقود الذكية وتحسينها لكفاءة الغاز للحفاظ على رسوم منخفضة وثقة عالية.",
                   "f1": "صانع السوق الآلي AMM", "f2": "مجمعات سيولة وزراعة",
                   "f3": "تداول مباشر من المحفظة", "f4": "عقود مدققة ومحسّنة للغاز",
                   "f5": "تخزين وجسور وتحليلات"},
        },
    },
    {
        "cat": "blockchain", "file": "p2p-exchange.html", "img": "trading",
        "title_key": "services.blockchain.p2p", "title_en": "P2P Exchange",
        "desc": "Peer-to-peer crypto platforms by Amatis that match buyers and sellers with escrow protection.",
        "c": {
            "en": {"subtitle": "Peer-to-peer platforms matching buyers and sellers.",
                   "p1": "We build P2P exchanges where users trade directly with each other. Offer walls, price matching, rating systems and secure escrow keep every deal fair and protected.",
                   "p2": "Support multiple payment methods and regions, with dispute resolution that keeps both sides confident.",
                   "f1": "Buyers & sellers matching", "f2": "Secure escrow protection",
                   "f3": "Reputation & rating system", "f4": "Multiple payment methods & regions",
                   "f5": "Dispute resolution workflow"},
            "de": {"subtitle": "Peer-to-Peer-Plattformen, die Käufer und Verkäufer zusammenbringen.",
                   "p1": "Wir bauen P2P-Börsen, bei denen Nutzer direkt miteinander handeln. Angebotswände, Preiszusammenführung, Bewertungssysteme und sichere Treuhand halten jedes Geschäft fair und geschützt.",
                   "p2": "Unterstützen Sie mehrere Zahlungsarten und Regionen – mit Streitbeilegung, die beiden Seiten Sicherheit gibt.",
                   "f1": "Käufer & Verkäufer zusammenführen", "f2": "Sichere Treuhand (Escrow)",
                   "f3": "Reputations- & Bewertungssystem", "f4": "Mehrere Zahlungsarten & Regionen",
                   "f5": "Streitbeilegungs-Workflow"},
            "fa": {"subtitle": "پلتفرم همتا‌به‌همتا که خریدار و فروشنده را به هم وصل می‌کند.",
                   "p1": "صرافی P2P می‌سازیم که کاربران مستقیم با هم معامله می‌کنند. ویترین پیشنهادها، تطبیق قیمت، سیستم امتیازدهی و اسکرو امن، هر معامله را منصفانه حفظ می‌کنند.",
                   "p2": "روش‌های پرداخت و مناطق مختلف را پشتیبانی می‌کنیم، با فرایند رسیدگی به اختلاف که هر دو طرف را مطمئن نگه می‌دارد.",
                   "f1": "تطبیق خریدار و فروشنده", "f2": "حفاظت امن اسکرو",
                   "f3": "سیستم اعتبار و امتیازدهی", "f4": "روش‌های پرداخت و مناطق متعدد",
                   "f5": "فرایند رسیدگی به اختلاف"},
            "ar": {"subtitle": "منصات نظير-لنظير تجمع المشترين والبائعين.",
                   "p1": "نبني بورصات P2P يتداول فيها المستخدمون مباشرة مع بعضهم. جدران العروض ومطابقة الأسعار وأنظمة التقييم والضمان الآمن تحافظ على عدالة كل صفقة.",
                   "p2": "ندعم وسائل دفع ومناطق متعددة، مع آلية لحل النزاعات تمنح الطرفين الثقة.",
                   "f1": "مطابقة المشترين والبائعين", "f2": "حماية الضمان الآمن Escrow",
                   "f3": "نظام السمعة والتقييم", "f4": "وسائل دفع ومناطق متعددة",
                   "f5": "سير عمل حل النزاعات"},
        },
    },
    {
        "cat": "blockchain", "file": "otc-exchange.html", "img": "finance",
        "title_key": "services.blockchain.otc", "title_en": "OTC Exchange",
        "desc": "OTC desks for large cryptocurrency trades by Amatis — privacy, liquidity and dedicated service.",
        "c": {
            "en": {"subtitle": "OTC desks for large, private trades.",
                   "p1": "For large trades that move markets, OTC is the answer. We build private over-the-counter desks with negotiated pricing, high liquidity and direct settlement between parties.",
                   "p2": "Handle institutional clients with dedicated accounts, transparency reports and professional service at every step.",
                   "f1": "Large-trade execution without slippage", "f2": "Negotiated pricing & liquidity",
                   "f3": "Direct settlement & custody options", "f4": "Institutional client accounts",
                   "f5": "Transparency & reporting tools"},
            "de": {"subtitle": "OTC-Desks für große, private Trades.",
                   "p1": "Für große Geschäfte, die Märkte bewegen, ist OTC die Lösung. Wir bauen private OTC-Desks mit ausgehandelten Preisen, hoher Liquidität und direkter Abwicklung zwischen den Parteien.",
                   "p2": "Bedienen Sie institutionelle Kunden mit dedizierten Konten, Transparenzberichten und professionellem Service in jedem Schritt.",
                   "f1": "Ausführung großer Trades ohne Slippage", "f2": "Verhandelbare Preise & Liquidität",
                   "f3": "Direkte Abwicklung & Verwahrung", "f4": "Institutionelle Kundenkonten",
                   "f5": "Transparenz- & Berichtstools"},
            "fa": {"subtitle": "میز معاملات OTC برای معاملات بزرگ و خصوصی.",
                   "p1": "برای معاملات بزرگی که بازار را جابه‌جا می‌کنند، OTC راه‌حل است. میز معاملات خصوصی با قیمت‌گذاری مذاکره‌ای، نقدینگی بالا و تسویه مستقیم بین طرفین می‌سازیم.",
                   "p2": "مشتریان نهادی را با حساب اختصاصی، گزارش شفافیت و خدمات حرفه‌ای در هر مرحله پشتیبانی می‌کنیم.",
                   "f1": "اجرای معاملات بزرگ بدون لغزش قیمت", "f2": "قیمت مذاکره‌ای و نقدینگی",
                   "f3": "تسویه مستقیم و گزینه‌های نگهداری", "f4": "حساب‌های مشتریان نهادی",
                   "f5": "ابزارهای شفافیت و گزارش‌گیری"},
            "ar": {"subtitle": "مكاتب OTC لصفقات كبيرة وخاصة.",
                   "p1": "للصفقات الكبيرة التي تحرّك الأسواق، OTC هو الحل. نبني مكاتب تداول خارج البورصة خاصة بتسعير تفاوضي وسيولة عالية وتسوية مباشرة بين الأطراف.",
                   "p2": "نخدم العملاء المؤسسيين بحسابات مخصصة وتقارير شفافية وخدمة احترافية في كل خطوة.",
                   "f1": "تنفيذ صفقات كبيرة دون انزلاق", "f2": "تسعير تفاوضي وسيولة",
                   "f3": "تسوية مباشرة وخيارات حفظ", "f4": "حسابات عملاء مؤسسيين",
                   "f5": "أدوات شفافية وتقارير"},
        },
    },
    {
        "cat": "blockchain", "file": "crypto-payment-gateway.html", "img": "payment",
        "title_key": "services.blockchain.gateway", "title_en": "Crypto Payment Gateway",
        "desc": "Crypto payment gateways by Amatis — accept digital assets in your store and business.",
        "c": {
            "en": {"subtitle": "Gateways to accept digital assets.",
                   "p1": "Let customers pay with crypto and still receive the funds you need. We build payment gateways with instant confirmations, automatic USD-pegged settlement and fiat conversion.",
                   "p2": "Plugins for major e-commerce platforms, flexible merchant APIs and a dashboard give you full control.",
                   "f1": "Instant on-chain confirmations", "f2": "Auto settlement & fiat conversion",
                   "f3": "E-commerce platform plugins", "f4": "Merchant APIs & webhooks",
                   "f5": "Merchant dashboard & reports"},
            "de": {"subtitle": "Gateways zum Akzeptieren digitaler Vermögenswerte.",
                   "p1": "Lassen Sie Kunden mit Krypto zahlen und erhalten Sie die Mittel, die Sie brauchen. Wir bauen Zahlungs-Gateways mit sofortigen Bestätigungen, automatischer Abrechnung und Fiat-Konvertierung.",
                   "p2": "Plugins für große E-Commerce-Plattformen, flexible Merchant-APIs und ein Dashboard geben Ihnen volle Kontrolle.",
                   "f1": "Sofortige On-Chain-Bestätigungen", "f2": "Automatische Abrechnung & Fiat-Umwandlung",
                   "f3": "Plugins für E-Commerce-Plattformen", "f4": "Merchant-APIs & Webhooks",
                   "f5": "Merchant-Dashboard & Berichte"},
            "fa": {"subtitle": "درگاه پرداخت برای پذیرش دارایی‌های دیجیتال.",
                   "p1": "به مشتریان اجازه دهید با کریپتو پرداخت کنند و همچنان وجوه موردنیازتان را دریافت کنید. درگاه پرداخت با تأیید لحظه‌ای، تسویه خودکار و تبدیل به ارز فیات می‌سازیم.",
                   "p2": "افزونه برای پلتفرم‌های بزرگ فروشگاهی، API منعطف برای پذیرندگان و داشبورد کامل در اختیارتان قرار می‌دهیم.",
                   "f1": "تأیید لحظه‌ای آن‌چین", "f2": "تسویه خودکار و تبدیل فیات",
                   "f3": "افزونه‌های پلتفرم‌های فروشگاهی", "f4": "API پذیرنده و وبهوک",
                   "f5": "داشبورد پذیرنده و گزارش‌ها"},
            "ar": {"subtitle": "بوابات دفع لقبول الأصول الرقمية.",
                   "p1": "أتح للعملاء الدفع بالعملات الرقمية مع استمرار حصولك على الأموال التي تحتاجها. نبني بوابات دفع بتأكيدات فورية وتسوية تلقائية مربوطة بالدولار وتحويل للعملات الورقية.",
                   "p2": "إضافات لمنصات التجارة الإلكترونية الكبرى وواجهات مرنة للتجار ولوحة تحكم تمنحك السيطرة الكاملة.",
                   "f1": "تأكيدات فورية على السلسلة", "f2": "تسوية تلقائية وتحويل للعملة الورقية",
                   "f3": "إضافات منصات التجارة الإلكترونية", "f4": "واجهات تاجر وWebhooks",
                   "f5": "لوحة تحكم التاجر والتقارير"},
        },
    },
    {
        "cat": "blockchain", "file": "smart-contracts.html", "img": "blockchain",
        "title_key": "services.blockchain.contracts", "title_en": "Smart Contracts & Tokens",
        "desc": "Smart contract and token development by Amatis — audited, secure and gas-optimized.",
        "c": {
            "en": {"subtitle": "Smart contract and token development.",
                   "p1": "We design and deploy on-chain logic for your project — from ERC/BEP tokens and NFTs to DAOs, staking and custom DeFi protocols. Security always comes first.",
                   "p2": "Every contract is audited, unit-tested and gas-optimized, with clear documentation your team can maintain with confidence.",
                   "f1": "Token creation (ERC-20, BEP-20, NFTs)", "f2": "Staking, DAOs & DeFi modules",
                   "f3": "Audited & unit-tested contracts", "f4": "Gas optimization & security best practices",
                   "f5": "Documentation & deployment support"},
            "de": {"subtitle": "Smart-Contract- und Token-Entwicklung.",
                   "p1": "Wir entwerfen und deployen On-Chain-Logik für Ihr Projekt – von ERC/BEP-Tokens und NFTs über DAOs und Staking bis zu eigenen DeFi-Protokollen. Sicherheit hat immer Priorität.",
                   "p2": "Jeder Contract wird auditiert, getestet und gas-optimiert – mit klarer Dokumentation, die Ihr Team sicher warten kann.",
                   "f1": "Token-Erstellung (ERC-20, BEP-20, NFTs)", "f2": "Staking, DAOs & DeFi-Module",
                   "f3": "Auditierte & getestete Contracts", "f4": "Gas-Optimierung & Sicherheitsstandards",
                   "f5": "Dokumentation & Deployment-Support"},
            "fa": {"subtitle": "توسعه قرارداد هوشمند و توکن.",
                   "p1": "منطق آن‌چین پروژه را طراحی و منتشر می‌کنیم — از توکن‌های ERC/BEP و NFT تا DAO، استیکینگ و پروتکل‌های سفارشی DeFi. امنیت همیشه اولویت اول است.",
                   "p2": "هر قرارداد حسابرسی، یونیت‌تست و بهینه‌شده برای گس است، با مستندات واضحی که تیم شما با اطمینان نگهداری کند.",
                   "f1": "ایجاد توکن (ERC-20، BEP-20، NFT)", "f2": "استیکینگ، DAO و ماژول‌های DeFi",
                   "f3": "قراردادهای حسابرسی‌شده و تست‌شده", "f4": "بهینه‌سازی گس و اصول امنیتی",
                   "f5": "مستندات و پشتیبانی استقرار"},
            "ar": {"subtitle": "تطوير العقود الذكية والرموز.",
                   "p1": "نصمم وننشر منطق السلسلة لمشروعك — من رموز ERC/BEP وNFT إلى DAO والتخزين وبروتوكولات DeFi مخصصة. الأمان دائمًا أولًا.",
                   "p2": "كل عقد مدقق ومختبَر ومحسّن للغاز، مع وثائق واضحة يمكن لفريقك صيانتها بثقة.",
                   "f1": "إنشاء الرموز (ERC-20 وBEP-20 وNFT)", "f2": "تخزين وDAO ووحدات DeFi",
                   "f3": "عقود مدققة ومختبَرة", "f4": "تحسين الغاز وأفضل ممارسات الأمان",
                   "f5": "توثيق ودعم النشر"},
        },
    },
    {
        "cat": "blockchain", "file": "airdrop-platform.html", "img": "ethereum",
        "title_key": "services.blockchain.airdrop", "title_en": "Airdrop Platform",
        "desc": "Airdrop and token distribution platforms by Amatis — secure, automated and anti-bot.",
        "c": {
            "en": {"subtitle": "Airdrop and token distribution platforms.",
                   "p1": "Reach thousands of wallets with a secure, automated airdrop. We build distribution platforms with eligibility rules, tasks and claims while keeping anti-bot measures and gas costs in check.",
                   "p2": "Analytics show exactly how your campaign performed, from eligible wallets to claimed tokens.",
                   "f1": "Automated token distribution", "f2": "Eligibility rules & task gates",
                   "f3": "Anti-bot & Sybil protection", "f4": "Claim pages & wallet integration",
                   "f5": "Campaign analytics & reports"},
            "de": {"subtitle": "Airdrop- und Token-Verteilungsplattformen.",
                   "p1": "Erreichen Sie Tausende Wallets mit einem sicheren, automatisierten Airdrop. Wir bauen Verteilungsplattformen mit Berechtigungsregeln, Aufgaben und Claims – mit Anti-Bot-Schutz und kontrollierten Gaskosten.",
                   "p2": "Analysen zeigen genau, wie Ihre Kampagne gelaufen ist – von berechtigten Wallets bis zu eingelösten Tokens.",
                   "f1": "Automatisierte Token-Verteilung", "f2": "Berechtigungsregeln & Aufgaben",
                   "f3": "Anti-Bot- & Sybil-Schutz", "f4": "Claim-Seiten & Wallet-Anbindung",
                   "f5": "Kampagnen-Analysen & Berichte"},
            "fa": {"subtitle": "پلتفرم ایردراپ و توزیع توکن.",
                   "p1": "با ایردراپی امن و خودکار به هزاران کیف پول برسید. پلتفرم توزیع با قوانین صلاحیت، تسک‌ها و کلایم می‌سازیم، در حالی که ضدباز ربات و هزینه گس را کنترل می‌کنیم.",
                   "p2": "آنالیتیکس دقیقاً عملکرد کمپین را نشان می‌دهد، از کیف پول‌های واجد شرایط تا توکن‌های کلایم‌شده.",
                   "f1": "توزیع خودکار توکن", "f2": "قوانین صلاحیت و دروازه‌های تسک",
                   "f3": "حفاظت در برابر ربات و Sybil", "f4": "صفحه کلایم و اتصال کیف پول",
                   "f5": "آنالیتیکس و گزارش کمپین"},
            "ar": {"subtitle": "منصات توزيع الرموز Airdrop.",
                   "p1": "وصل إلى آلاف المحافظ عبر توزيع آمن ومؤتمت. نبني منصات توزيع بقواعد الأهلية والمهام والمطالبات مع حماية من البوتات وضبط تكاليف الغاز.",
                   "p2": "تبيّن التحليلات بدقة أداء حملتك، من المحافظ المؤهلة إلى الرموز المطالب بها.",
                   "f1": "توزيع رموز مؤتمت", "f2": "قواعد أهلية وبوابات مهام",
                   "f3": "حماية من البوتات وهجمات Sybil", "f4": "صفحات المطالبة وتكامل المحفظة",
                   "f5": "تحليلات الحملات وتقارير"},
        },
    },
    {
        "cat": "blockchain", "file": "exchange-app.html", "img": "money",
        "title_key": "services.blockchain.app", "title_en": "Exchange App",
        "desc": "Crypto exchange mobile apps by Amatis — real-time charts, trading and portfolio management.",
        "c": {
            "en": {"subtitle": "Exchange apps with charts and trading.",
                   "p1": "Take your exchange to mobile. We build trading apps with real-time charts, order placement, portfolio tracking and secure biometric login that your users will trust on the go.",
                   "p2": "Multi-factor authentication, price alerts and a clean interface make trading simple enough for everyone.",
                   "f1": "Real-time charts & market data", "f2": "Order placement & management",
                   "f3": "Portfolio & balance tracking", "f4": "Biometric login & 2FA",
                   "f5": "Price alerts & notifications"},
            "de": {"subtitle": "Exchange-Apps mit Charts und Trading.",
                   "p1": "Bringen Sie Ihre Börse auf Mobilgeräte. Wir bauen Trading-Apps mit Echtzeit-Charts, Order-Eingabe, Portfolio-Tracking und sicheren biometrischen Login – vertrauenswürdig unterwegs.",
                   "p2": "Multi-Faktor-Authentifizierung, Preisalarme und eine klare Oberfläche machen das Trading einfach für alle.",
                   "f1": "Echtzeit-Charts & Marktdaten", "f2": "Order-Eingabe & -Verwaltung",
                   "f3": "Portfolio- & Kontostand-Tracking", "f4": "Biometrischer Login & 2FA",
                   "f5": "Preisalarme & Benachrichtigungen"},
            "fa": {"subtitle": "اپلیکیشن صرافی با چارت و معامله.",
                   "p1": "صرافی خود را به موبایل ببرید. اپلیکیشن معاملاتی با چارت لحظه‌ای، ثبت سفارش، رهگیری پورتفویو و ورود امن بیومتریک می‌سازیم که کاربران در هر جا به آن اعتماد کنند.",
                   "p2": "احراز هویت دومرحله‌ای، هشدار قیمت و رابط کاربری ساده، معامله را برای همه ساده می‌کند.",
                   "f1": "چارت لحظه‌ای و داده بازار", "f2": "ثبت و مدیریت سفارش",
                   "f3": "رهگیری پورتفویو و موجودی", "f4": "ورود بیومتریک و تأیید دومرحله‌ای",
                   "f5": "هشدار قیمت و نوتیفیکیشن"},
            "ar": {"subtitle": "تطبيقات البورصات مع رسوم بيانية وتداول.",
                   "p1": "انقل بورصتك إلى الجوال. نبني تطبيقات تداول برسوم لحظية ووضع أوامر وتتبع للمحافظ ودخول آمن بالقياسات الحيوية يثق به المستخدمون في أي مكان.",
                   "p2": "مصادقة متعددة العوامل وتنبيهات أسعار وواجهة نظيفة تجعل التداول سهلًا للجميع.",
                   "f1": "رسوم لحظية وبيانات السوق", "f2": "وضع الأوامر وإدارتها",
                   "f3": "تتبع المحفظة والرصيد", "f4": "دخول حيوي و2FA",
                   "f5": "تنبيهات أسعار وإشعارات"},
        },
    },
    # ---------------- MORE SERVICES ----------------
    {
        "cat": "more", "file": "uiux-design.html", "img": "design",
        "title_key": "services.more.uiux", "title_en": "UI/UX Design",
        "desc": "UI/UX design services by Amatis — product and interface design users love.",
        "c": {
            "en": {"subtitle": "Product and interface design users love.",
                   "p1": "Great products start with great design. Our designers research your users, map their journeys and craft interfaces that are clear, beautiful and easy to use across every screen.",
                   "p2": "From wireframes and prototypes to full design systems, we hand developers precise specs that bring your idea to life without friction.",
                   "f1": "User research & journey mapping", "f2": "Wireframes & interactive prototypes",
                   "f3": "Design systems & UI kits", "f4": "Mobile & responsive design",
                   "f5": "Usability testing & iteration"},
            "de": {"subtitle": "Produkt- und Interface-Design, das Nutzer lieben.",
                   "p1": "Große Produkte beginnen mit großem Design. Unsere Designer erforschen Ihre Nutzer, kartieren ihre Wege und gestalten klare, schöne und benutzerfreundliche Oberflächen für jede Bildschirmgröße.",
                   "p2": "Vom Wireframe über Prototypen bis zu kompletten Design-Systemen liefern wir Entwicklern präzise Spezifikationen, die Ihre Idee reibungslos umsetzen.",
                   "f1": "Nutzerforschung & Journey-Mapping", "f2": "Wireframes & interaktive Prototypen",
                   "f3": "Design-Systeme & UI-Kits", "f4": "Mobiles & responsives Design",
                   "f5": "Usability-Tests & Iteration"},
            "fa": {"subtitle": "طراحی محصول و رابط کاربری که کاربران دوستش دارند.",
                   "p1": "محصولات عالی با طراحی عالی شروع می‌شوند. طراحان ما کاربران را مطالعه می‌کنند، سفرشان را ترسیم می‌کنند و رابط‌هایی واضح، زیبا و آسان برای همه صفحه‌ها می‌سازند.",
                   "p2": "از وایرفریم و نمونه تعاملی تا سیستم طراحی کامل، مشخصات دقیقی به توسعه‌دهندگان می‌دهیم تا ایده شما بدون اصطکاک به واقعیت بپیوندد.",
                   "f1": "تحقیق کاربر و ترسیم سفر", "f2": "وایرفریم و نمونه تعاملی",
                   "f3": "سیستم طراحی و UI کیت", "f4": "طراحی موبایل و واکنش‌گرا",
                   "f5": "تست قابلیت استفاده و بهبود تکراری"},
            "ar": {"subtitle": "تصميم المنتجات والواجهات الذي يعشقه المستخدمون.",
                   "p1": "تبدأ المنتجات العظيمة بالتصميم العظيم. يدرس مصممونا المستخدمين ويرسمون رحلاتهم ويبتكرون واجهات واضحة وجميلة وسهلة الاستخدام على كل شاشة.",
                   "p2": "من الهياكل والنماذج التفاعلية إلى أنظمة التصميم الكاملة، نسلم المطورين مواصفات دقيقة تُحقق فكرتك دون احتكاك.",
                   "f1": "بحث المستخدمين ورسم الرحلات", "f2": "هياكل ونماذج تفاعلية",
                   "f3": "أنظمة تصميم ومجموعات واجهات", "f4": "تصميم متجاوب للجوال",
                   "f5": "اختبار قابلية الاستخدام والتكرار"},
        },
    },
    {
        "cat": "more", "file": "seo-marketing.html", "img": "marketing",
        "title_key": "services.more.seo", "title_en": "SEO & Digital Marketing",
        "desc": "SEO and digital marketing by Amatis — grow organic traffic, engagement and sales.",
        "c": {
            "en": {"subtitle": "Grow organic traffic and sales.",
                   "p1": "Visibility brings customers. We build SEO and digital marketing strategies that improve rankings, launch effective campaigns and turn traffic into loyal paying customers.",
                   "p2": "From technical SEO and content strategy to paid ads and analytics, everything is measured and continuously improved.",
                   "f1": "Technical & on-page SEO", "f2": "Content strategy & link building",
                   "f3": "Paid advertising campaigns", "f4": "Conversion rate optimization",
                   "f5": "Analytics, reporting & growth"},
            "de": {"subtitle": "Organischen Traffic und Umsatz steigern.",
                   "p1": "Sichtbarkeit bringt Kunden. Wir entwickeln SEO- und Digital-Marketing-Strategien, die Rankings verbessern, Kampagnen starten und Traffic in treue zahlende Kunden verwandeln.",
                   "p2": "Von technischem SEO und Content-Strategie bis zu bezahlter Werbung und Analysen – alles wird gemessen und laufend verbessert.",
                   "f1": "Technisches & On-Page-SEO", "f2": "Content-Strategie & Linkbuilding",
                   "f3": "Bezahlte Werbekampagnen", "f4": "Conversion-Rate-Optimierung",
                   "f5": "Analysen, Reporting & Wachstum"},
            "fa": {"subtitle": "افزایش ترافیک ارگانیک و فروش.",
                   "p1": "دیده شدن مشتری می‌آورد. استراتژی‌های سئو و بازاریابی دیجیتال می‌سازیم که رتبه را بهتر، کمپین‌ها را مؤثر و ترافیک را به مشتری وفادار تبدیل می‌کنند.",
                   "p2": "از سئوی فنی و استراتژی محتوا تا تبلیغات کلیکی و آنالیتیکس، همه چیز سنجیده و مدام بهبود می‌یابد.",
                   "f1": "سئوی فنی و داخلی", "f2": "استراتژی محتوا و لینک‌سازی",
                   "f3": "کمپین‌های تبلیغاتی", "f4": "بهینه‌سازی نرخ تبدیل",
                   "f5": "آنالیتیکس، گزارش و رشد"},
            "ar": {"subtitle": "زيادة الزيارات العضوية والمبيعات.",
                   "p1": "الظهور يجلب العملاء. نبني استراتيجيات SEO وتسويق رقمي تحسّن الترتيب وتطلق حملات فعّالة وتحوّل الزيارات إلى عملاء مخلصين.",
                   "p2": "من الـSEO التقني واستراتيجية المحتوى إلى الإعلانات المدفوعة والتحليلات، كل شيء يُقاس ويُحسّن باستمرار.",
                   "f1": "تحسين محركات البحث الفني والداخلي", "f2": "استراتيجية محتوى وبناء روابط",
                   "f3": "حملات إعلانية مدفوعة", "f4": "تحسين معدل التحويل",
                   "f5": "تحليلات وتقارير ونمو"},
        },
    },
    {
        "cat": "more", "file": "dashboards-admin.html", "img": "analytics",
        "title_key": "services.more.dashboards", "title_en": "Dashboards & Admin Panels",
        "desc": "Dashboards and admin panels by Amatis — run your business with clear data and full control.",
        "c": {
            "en": {"subtitle": "Admin panels to run your business with data.",
                   "p1": "Decisions are faster with clear data. We design and build dashboards and admin panels tailored to your workflow — from KPI overviews to deep reporting and operations tools.",
                   "p2": "Role-based access, data exports and integrations connect your tools, so your team works in one place.",
                   "f1": "KPI dashboards & data visualization", "f2": "Operations, users & roles management",
                   "f3": "Reports & data export", "f4": "Integrations with your tools",
                   "f5": "Role-based access control"},
            "de": {"subtitle": "Admin-Panels, um Ihr Business mit Daten zu führen.",
                   "p1": "Mit klaren Daten sind Entscheidungen schneller. Wir gestalten und entwickeln Dashboards und Admin-Panels passend zu Ihrem Workflow – von KPI-Übersichten bis zu tiefen Berichten und Operations-Tools.",
                   "p2": "Rollenbasierte Zugriffe, Datenexporte und Integrationen verbinden Ihre Tools, sodass Ihr Team an einem Ort arbeitet.",
                   "f1": "KPI-Dashboards & Datenvisualisierung", "f2": "Operations-, Nutzer- & Rollenverwaltung",
                   "f3": "Berichte & Datenexport", "f4": "Integration Ihrer Tools",
                   "f5": "Rollenbasierte Zugriffskontrolle"},
            "fa": {"subtitle": "پنل مدیریت برای اداره کسب‌وکار با داده.",
                   "p1": "با داده‌های شفاف تصمیم‌گیری سریع‌تر است. داشبورد و پنل مدیریت متناسب با فرایند شما طراحی و ساخته می‌شود — از نمای KPI تا گزارش‌های عمیق و ابزارهای عملیاتی.",
                   "p2": "دسترسی نقش‌محور، خروجی داده و یکپارچه‌سازی‌ها ابزارهای شما را به هم متصل می‌کنند تا تیم در یک جا کار کند.",
                   "f1": "داشبورد KPI و مصورسازی داده", "f2": "مدیریت عملیات، کاربران و نقش‌ها",
                   "f3": "گزارش‌ها و خروجی داده", "f4": "یکپارچه‌سازی با ابزارهای شما",
                   "f5": "کنترل دسترسی نقش‌محور"},
            "ar": {"subtitle": "لوحات إدارة لتشغيل أعمالك بالبيانات.",
                   "p1": "القرارات أسرع مع البيانات الواضحة. نصمم ونبني لوحات التحكم وإدارة مخصصة لسير عملك — من نظرة عامة على مؤشرات الأداء إلى تقارير عميقة وأدوات تشغيلية.",
                   "p2": "الوصول حسب الأدوار وتصدير البيانات والتكاملات تربط أدواتك ليعمل فريقك في مكان واحد.",
                   "f1": "لوحات مؤشرات وتصوير البيانات", "f2": "إدارة العمليات والمستخدمين والأدوار",
                   "f3": "تقارير وتصدير البيانات", "f4": "تكاملات مع أدواتك",
                   "f5": "التحكم في الوصول حسب الدور"},
        },
    },
    {
        "cat": "more", "file": "maintenance-support.html", "img": "computer",
        "title_key": "services.more.support", "title_en": "Maintenance & Support",
        "desc": "Maintenance and support by Amatis — hosting, monitoring and support that keeps everything running.",
        "c": {
            "en": {"subtitle": "Hosting and support that keeps everything running.",
                   "p1": "Your product should keep improving after launch. We provide hosting, monitoring, updates and proactive maintenance so your website or app stays fast, secure and available.",
                   "p2": "Our support team handles bug fixes, feature additions and improvements with clear SLAs and transparent reporting.",
                   "f1": "Reliable hosting & monitoring", "f2": "Security patches & regular updates",
                   "f3": "Performance tuning & optimization", "f4": "Bug fixes & feature additions",
                   "f5": "SLA-backed support & reporting"},
            "de": {"subtitle": "Hosting und Support, der alles am Laufen hält.",
                   "p1": "Ihr Produkt soll auch nach dem Launch besser werden. Wir bieten Hosting, Monitoring, Updates und proaktive Wartung, damit Ihre Website oder App schnell, sicher und verfügbar bleibt.",
                   "p2": "Unser Support-Team kümmert sich um Bugfixes, Funktionserweiterungen und Verbesserungen mit klaren SLAs und transparenter Berichterstattung.",
                   "f1": "Zuverlässiges Hosting & Monitoring", "f2": "Sicherheits-Updates & regelmäßige Wartung",
                   "f3": "Performance-Optimierung", "f4": "Bugfixes & Funktionserweiterungen",
                   "f5": "Support mit SLA & Reporting"},
            "fa": {"subtitle": "هاستینگ و پشتیبانی که همه چیز را سرپا نگه می‌دارد.",
                   "p1": "محصول شما باید بعد از عرضه هم بهتر شود. هاستینگ، مانیتورینگ، به‌روزرسانی و نگهداری پیشگیرانه ارائه می‌کنیم تا وب‌سایت یا اپ شما سریع، امن و در دسترس بماند.",
                   "p2": "تیم پشتیبانی ما با SLAهای مشخص و گزارش‌دهی شفاف، باگ‌ها، افزوده‌ها و بهبودها را مدیریت می‌کند.",
                   "f1": "هاستینگ مطمئن و مانیتورینگ", "f2": "اصلاحات امنیتی و به‌روزرسانی منظم",
                   "f3": "بهینه‌سازی و تنظیم عملکرد", "f4": "رفع باگ و افزودن قابلیت",
                   "f5": "پشتیبانی با SLA و گزارش‌دهی"},
            "ar": {"subtitle": "استضافة ودعم يحافظان على استمرار كل شيء.",
                   "p1": "يجب أن يتحسن منتجك بعد الإطلاق. نوفر الاستضافة والمراقبة والتحديثات والصيانة الاستباقية ليبقى موقعك أو تطبيقك سريعًا وآمنًا ومتاحًا.",
                   "p2": "يتولى فريق الدعم لدينا إصلاح الأخطاء وإضافة الميزات والتحسينات باتفاقيات مستوى خدمة واضحة وتقارير شفافة.",
                   "f1": "استضافة موثوقة ومراقبة", "f2": "تصحيحات أمنية وتحديثات منتظمة",
                   "f3": "ضبط وتحسين الأداء", "f4": "إصلاح الأخطاء وإضافة الميزات",
                   "f5": "دعم باتفاقيات مستوى خدمة وتقارير"},
        },
    },
]

SERVICES_ALL = SERVICES_EXTRA