# -*- coding: utf-8 -*-
# Service page content for amatisberry.ir — one entry per service.
# Each entry: cat (category), file (generated filename), img (flickr keyword),
# desc (en meta description), title_key (existing i18n nav key for the name),
# title_en (static English fallback), c[lang] keys: subtitle, p1, p2, f1..f5.

SERVICES = [
    # ---------------- APPS ----------------
    {
        "cat": "apps", "file": "android-app.html", "img": "android",
        "title_key": "services.apps.android", "title_en": "Android App",
        "desc": "Native Android application development by AmatisBerry — Kotlin, modern architecture, Play Store release and long-term support.",
        "c": {
            "en": {"subtitle": "Native Android applications built with Kotlin, from MVP to mature product.",
                   "p1": "Our Android team ships high-performance apps using Kotlin and modern architecture patterns such as MVVM and clean architecture. We cover the full lifecycle — discovery, UI/UX, development, Play Store publishing and post-launch iteration.",
                   "p2": "From MVPs to large-scale products with offline mode, push notifications, payments and analytics, we build apps your users will keep coming back to.",
                   "f1": "Native development with Kotlin & Jetpack Compose", "f2": "Clean architecture and rigorous code review",
                   "f3": "Play Store release & app store optimization", "f4": "Push notifications, payments & analytics",
                   "f5": "Continuous updates and long-term support"},
            "de": {"subtitle": "Native-Android-Apps mit Kotlin – vom MVP bis zum ausgereiften Produkt.",
                   "p1": "Unser Android-Team entwickelt leistungsfähige Apps mit Kotlin und modernen Architekturmustern wie MVVM und Clean Architecture. Wir begleiten den gesamten Lebenszyklus – von der Konzeption über UI/UX und Entwicklung bis zur Veröffentlichung im Play Store sowie zur Weiterentwicklung nach dem Launch.",
                   "p2": "Vom MVP bis zu großen Produkten mit Offline-Modus, Push-Benachrichtigungen, Zahlungen und Analysen bauen wir Apps, zu denen Ihre Nutzer gern zurückkehren.",
                   "f1": "Natives Android mit Kotlin & Jetpack Compose", "f2": "Clean Architecture und gründliches Code-Review",
                   "f3": "Play-Store-Veröffentlichung & ASO", "f4": "Push-Benachrichtigungen, Zahlungen & Analysen",
                   "f5": "Kontinuierliche Updates und langfristiger Support"},
            "fa": {"subtitle": "اپلیکیشن‌های اندروید نیتیو با کاتلین، از MVP تا محصول کامل.",
                   "p1": "تیم اندروید ما با کاتلین و معماری‌های مدرن مانند MVVM و Clean Architecture اپلیکیشن‌هایی پرسرعت و باکیفیت می‌سازد. کل چرخه را پوشش می‌دهیم — از ایده و UI/UX و توسعه تا انتشار در گوگل‌پلی و بهبود مداوم پس از عرضه.",
                   "p2": "از MVP تا محصولات بزرگ با حالت آفلاین، نوتیفیکیشن، پرداخت امن و آنالیتیکس، اپلیکیشنی می‌سازیم که کاربران بارها و بارها به آن برمی‌گردند.",
                   "f1": "توسعه نیتیو با کاتلین و Jetpack Compose", "f2": "معماری تمیز و بررسی دقیق کد",
                   "f3": "انتشار در گوگل‌پلی و سئوی اپ‌استور", "f4": "نوتیفیکیشن، پرداخت و آنالیتیکس",
                   "f5": "آپدیت مستمر و پشتیبانی بلندمدت"},
            "ar": {"subtitle": "تطبيقات أندرويد أصلية مبنية بلغة Kotlin، من فكرة MVP إلى منتج متكامل.",
                   "p1": "يبني فريقنا تطبيقات أندرويد عالية الأداء باستخدام Kotlin وأنماط معمارية حديثة مثل MVVM وClean Architecture. نغطي دورة الحياة كاملة — من الفكرة وتصميم الواجهة والتطوير وحتى النشر في متجر Play والتطوير المستمر.",
                   "p2": "من النسخ الأولية حتى المنتجات الكبيرة مع وضع عدم الاتصال والإشعارات والمدفوعات والتحليلات، نبني تطبيقات يعود إليها المستخدمون دائمًا.",
                   "f1": "تطوير أصلي مع Kotlin وJetpack Compose", "f2": "معمارية نظيفة ومراجعة دقيقة للكود",
                   "f3": "النشر في متجر Play وتحسين الظهور", "f4": "إشعارات ومدفوعات وتحليلات",
                   "f5": "تحديثات مستمرة ودعم طويل الأمد"},
        },
    },
    {
        "cat": "apps", "file": "ios-app.html", "img": "smartphone",
        "title_key": "services.apps.ios", "title_en": "iOS App",
        "desc": "Native iOS application development by AmatisBerry — Swift, SwiftUI, App Store polish and ongoing support.",
        "c": {
            "en": {"subtitle": "Native iOS apps with Swift and SwiftUI, polished to App Store standards.",
                   "p1": "We design and build iOS apps for iPhone and iPad with Swift and SwiftUI, following Apple's Human Interface Guidelines. From prototype to App Store review, we handle even the smallest detail of the experience.",
                   "p2": "Whether it is a consumer app, a service platform or an enterprise tool, we deliver fluid, accessible and delightful apps that earn five-star reviews.",
                   "f1": "Swift & SwiftUI native development", "f2": "Apple Design values & polished UX",
                   "f3": "App Store submission & review handling", "f4": "In-app purchases, iCloud & push",
                   "f5": "Performance tuning and ongoing maintenance"},
            "de": {"subtitle": "Native-iOS-Apps mit Swift und SwiftUI, auf App-Store-Niveau poliert.",
                   "p1": "Wir gestalten und entwickeln iOS-Apps für iPhone und iPad mit Swift und SwiftUI und folgen dabei den Human Interface Guidelines von Apple. Vom Prototyp bis zur App-Store-Freigabe kümmern wir uns um jedes Detail der Nutzererfahrung.",
                   "p2": "Ob Konsum-App, Service-Plattform oder Unternehmenslösung – wir liefern flüssige, barrierefreie Apps, die zu begeisterten Bewertungen führen.",
                   "f1": "Natives Swift- & SwiftUI-Development", "f2": "Apple-Design-Standards & hochwertige UX",
                   "f3": "App-Store-Einreichung & Prüfung", "f4": "In-App-Käufe, iCloud & Push",
                   "f5": "Performance-Optimierung und laufende Pflege"},
            "fa": {"subtitle": "اپلیکیشن‌های iOS نیتیو با Swift و SwiftUI، با استانداردهای اپ‌استور.",
                   "p1": "اپلیکیشن‌های iOS آیفون و آیپد را با Swift و SwiftUI و بر اساس Human Interface Guidelines اپل طراحی و توسعه می‌دهیم. از نمونه اولیه تا تأیید اپ‌استور، به تک‌تک جزئیات تجربه کاربر توجه می‌کنیم.",
                   "p2": "چه اپ مصرفی باشد چه پلتفرم خدماتی و چه ابزار سازمانی، اپلیکیشنی روان، در دسترس و دوست‌داشتنی تحویل می‌دهیم که نظرات عالی می‌گیرد.",
                   "f1": "توسعه نیتیو با Swift و SwiftUI", "f2": "استانداردهای طراحی اپل و تجربه کاربر درخشان",
                   "f3": "ارسال و تأیید در اپ‌استور", "f4": "خرید درون‌برنامه، iCloud و نوتیفیکیشن",
                   "f5": "بهینه‌سازی سرعت و نگهداری مستمر"},
            "ar": {"subtitle": "تطبيقات iOS أصلية بتقنيتي Swift وSwiftUI، باحترافية معايير متجر Apple.",
                   "p1": "نصمم ونبني تطبيقات iOS للآيفون والآيباد باستخدام Swift وSwiftUI، متّبعين إرشادات الواجهة البشرية في Apple. من النموذج الأولي حتى مراجعة متجر التطبيقات، نعتني بأدق تفاصيل التجربة.",
                   "p2": "سواء كان تطبيقًا استهلاكيًا أو منصة خدمات أو أداة مؤسسية، نقدّم تطبيقات سلسة وواضحة وتجربة ممتعة تستحق التقييمات الخمس نجوم.",
                   "f1": "تطوير أصلي بـ Swift وSwiftUI", "f2": "قيم تصميم Apple وتجربة مستخدم مصقولة",
                   "f3": "تقديم التطبيق لمتجر App Store واجتياز المراجعة", "f4": "المشتريات داخل التطبيق وiCloud والإشعارات",
                   "f5": "ضبط الأداء وصيانة مستمرة"},
        },
    },
    {
        "cat": "apps", "file": "web-app-pwa.html", "img": "website",
        "title_key": "services.apps.pwa", "title_en": "Web App & PWA",
        "desc": "Fast, installable web applications and PWAs by AmatisBerry — one codebase, every device, offline-ready.",
        "c": {
            "en": {"subtitle": "Fast, installable web apps and PWAs that work on any device and browser.",
                   "p1": "Progressive Web Apps combine the reach of the web with the feel of a native app. We build installable, offline-capable and lightning-fast web applications using modern stacks like Next.js and React.",
                   "p2": "One codebase, every device — fewer app-store costs, instant updates and a lower barrier for users to start using your product.",
                   "f1": "Installable & offline-ready (PWA)", "f2": "Modern React / Next.js architecture",
                   "f3": "Push notifications & background sync", "f4": "Fast loads and SEO-friendly rendering",
                   "f5": "One codebase for all platforms"},
            "de": {"subtitle": "Schnelle, installierbare Web-Apps und PWAs für jedes Gerät und jeden Browser.",
                   "p1": "Progressive Web Apps verbinden die Reichweite des Webs mit dem Gefühl einer nativen App. Wir entwickeln installierbare, offline-fähige und extrem schnelle Web-Apps mit modernen Technologien wie Next.js und React.",
                   "p2": "Eine Codebasis, jedes Gerät – weniger Store-Kosten, sofortige Updates und niedrige Einstiegshürden für Ihre Nutzer.",
                   "f1": "Installierbar & offline-fähig (PWA)", "f2": "Moderne React/Next.js-Architektur",
                   "f3": "Push-Benachrichtigungen & Hintergrund-Sync", "f4": "Schnelle Ladezeiten & SEO-freundlich",
                   "f5": "Eine Codebasis für alle Plattformen"},
            "fa": {"subtitle": "وب‌اپلیکیشن‌ها و PWAهای سریع و قابل نصب که روی هر دستگاهی کار می‌کنند.",
                   "p1": "Progressive Web Appها دسترسی وب را با حس اپلیکیشن نیتیو ترکیب می‌کنند. با استک‌های مدرن مثل Next.js و React، وب‌اپلیکیشن‌هایی قابل نصب، آفلاین و فوق‌العاده سریع می‌سازیم.",
                   "p2": "یک کدبیس، همه دستگاه‌ها — هزینه کمتر اپ‌استور، آپدیت فوری و مانع کمتر برای شروع استفاده کاربران از محصول شما.",
                   "f1": "قابل نصب و کارکرد آفلاین (PWA)", "f2": "معماری مدرن React و Next.js",
                   "f3": "نوتیفیکیشن و همگام‌سازی پس‌زمینه", "f4": "بارگذاری سریع و سئوی مطلوب",
                   "f5": "یک کدبیس برای همه پلتفرم‌ها"},
            "ar": {"subtitle": "تطبيقات ويب سريعة قابلة للتثبيت وتطبيقات PWA تعمل على أي جهاز وفي أي متصفح.",
                   "p1": "تجمع تطبيقات الويب التقدمية PWA بين انتشار الويب وشعور التطبيق الأصلي. ننشئ تطبيقات ويب قابلة للتثبيت وتعمل دون اتصال وسريعة جدًا باستخدام تقنيات حديثة مثل Next.js وReact.",
                   "p2": "قاعدة كود واحدة لكل الأجهزة — تكاليف أقل لمتاجر التطبيقات وتحديثات فورية وحاجز أقل ليبدأ المستخدمون باستخدام منتجك.",
                   "f1": "قابل للتثبيت ويعمل دون اتصال", "f2": "معمارية حديثة بـ React وNext.js",
                   "f3": "إشعارات ومزامنة في الخلفية", "f4": "تحميل سريع ومتوافق مع محركات البحث",
                   "f5": "قاعدة كود واحدة لكل المنصات"},
        },
    },
    {
        "cat": "apps", "file": "ecommerce-app.html", "img": "shopping",
        "title_key": "services.apps.ecom", "title_en": "E-commerce App",
        "desc": "Feature-rich mobile shopping apps by AmatisBerry — carts, secure payments, orders and push notifications.",
        "c": {
            "en": {"subtitle": "Feature-rich shopping apps with carts, payments, orders and push notifications.",
                   "p1": "We build native mobile stores that convert. Product catalogs, smart search, smooth checkout, order tracking, wishlists and push offers are all engineered for performance and retention.",
                   "p2": "Integrate local and international payment gateways, loyalty programs and marketing automation so your store grows with every release.",
                   "f1": "Catalog, search & smart product filters", "f2": "Secure one-tap checkout",
                   "f3": "Order tracking, wishlist & reviews", "f4": "Payment gateways & loyalty programs",
                   "f5": "Push campaigns & retention analytics"},
            "de": {"subtitle": "Funktionsreiche Shopping-Apps mit Warenkorb, Zahlungen, Bestellungen und Push-Benachrichtigungen.",
                   "p1": "Wir entwickeln native Mobile-Stores, die konvertieren. Produktkataloge, intelligente Suche, reibungsloser Checkout, Sendungsverfolgung, Wunschliste und Push-Angebote – alles für Leistung und Kundenbindung optimiert.",
                   "p2": "Integrieren Sie lokale und internationale Zahlungsanbieter, Treueprogramme und Marketing-Automatisierung, damit Ihr Store mit jedem Release wächst.",
                   "f1": "Katalog, Suche & smarte Filter", "f2": "Sicherer One-Tap-Checkout",
                   "f3": "Bestellverfolgung, Wunschliste & Bewertungen", "f4": "Zahlungsanbieter & Treueprogramme",
                   "f5": "Push-Kampagnen & Kundenbindungs-Analysen"},
            "fa": {"subtitle": "اپلیکیشن‌های فروشگاهی کامل با سبد خرید، پرداخت، سفارش و نوتیفیکیشن.",
                   "p1": "فروشگاه‌های موبایل نیتیو می‌سازیم که واقعاً فروش ایجاد می‌کنند. کاتالوگ محصول، جستجوی هوشمند، تسویه‌حساب روان، رهگیری سفارش، علاقه‌مندی و پیام‌های فروش — همه برای کارایی و نگه‌داشت کاربر بهینه شده‌اند.",
                   "p2": "درگاه‌های پرداخت داخلی و بین‌المللی، برنامه‌های وفاداری و اتوماسیون بازاریابی را یکپارچه می‌کنیم تا فروشگاه شما با هر نسخه رشد کند.",
                   "f1": "کاتالوگ، جستجو و فیلترهای هوشمند", "f2": "تسویه‌حساب امن با یک لمس",
                   "f3": "رهگیری سفارش، علاقه‌مندی و نظرات", "f4": "درگاه‌های پرداخت و برنامه‌های وفاداری",
                   "f5": "کمپین‌های نوتیفیکیشن و آنالیز نگه‌داشت"},
            "ar": {"subtitle": "تطبيقات تسوق غنية بالوظائف — سلة، مدفوعات، طلبات وإشعارات فورية.",
                   "p1": "نبني متاجر موبايل أصلية تحقق المبيعات. كتالوجات المنتجات والبحث الذكي والدفع السلس وتتبع الطلبات وقائمة الأمنيات وعروض الإشعارات — كلها مصممة للأداء والاحتفاظ بالعملاء.",
                   "p2": "ندمج بوابات الدفع المحلية والدولية وبرامج الولاء وأتمتة التسويق لينمو متجرك مع كل إصدار.",
                   "f1": "كتالوج وبحث وفلترة ذكية للمنتجات", "f2": "دفع آمن بلمسة واحدة",
                   "f3": "تتبع الطلبات وقائمة الأمنيات والتقييمات", "f4": "بوابات دفع وبرامج ولاء",
                   "f5": "حملات إشعارات وتحليلات احتفاظ"},
        },
    },
    {
        "cat": "apps", "file": "classifieds-app.html", "img": "marketplace",
        "title_key": "services.apps.classifieds", "title_en": "Classifieds App",
        "desc": "Classifieds and listing apps built by AmatisBerry with smart search, chat, filters and secure posting.",
        "c": {
            "en": {"subtitle": "Classifieds and listing apps with chat, search, filters and secure posting.",
                   "p1": "From vehicle and property listings to job boards and second-hand marketplaces, we build classifieds apps that keep buyers and sellers engaged. Features like verified accounts, in-app chat and location-based search are built in.",
                   "p2": "Revenue-ready with featured listings, boosts and premium memberships, tuned for trust and high engagement.",
                   "f1": "Smart, location-aware search & filters", "f2": "In-app chat & contact management",
                   "f3": "Verified accounts & safe posting flow", "f4": "Featured listings, boosts & memberships",
                   "f5": "Moderation & analytics dashboard"},
            "de": {"subtitle": "Kleinanzeigen- und Listing-Apps mit Chat, Suche, Filtern und sicherer Veröffentlichung.",
                   "p1": "Von Fahrzeug- und Immobilienanzeigen über Jobbörsen bis zu Gebrauchtwaren – wir bauen Kleinanzeigen-Apps, die Käufer und Verkäufer aktiv halten. Verifizierte Konten, In-App-Chat und ortsbezogene Suche sind integriert.",
                   "p2": "Umsatzbereit mit Top-Platzierungen, Boost-Tools und Premium-Mitgliedschaften – optimiert für Vertrauen und Engagement.",
                   "f1": "Smarte, ortsbezogene Suche & Filter", "f2": "In-App-Chat & Kontaktverwaltung",
                   "f3": "Verifizierte Konten & sicherer Inserats-Flow", "f4": "Top-Anzeigen, Boosts & Mitgliedschaften",
                   "f5": "Moderation & Analyse-Dashboard"},
            "fa": {"subtitle": "اپلیکیشن‌های آگهی و فهرست با چت، جستجو، فیلتر و انتشار امن.",
                   "p1": "از آگهی خودرو و املاک گرفته تا کاریابی و بازار دست‌دوم، اپلیکیشن آگهی می‌سازیم که خریدار و فروشنده را فعال نگه می‌دارد. حساب‌های تأییدشده، چت درون‌برنامه و جستجوی موقعیت‌محور از پایه ساخته می‌شوند.",
                   "p2": "آماده درآمدزایی با آگهی ویژه، برجسته‌سازی و عضویت‌های ویژه؛ طراحی‌شده برای اعتماد و تعامل بالا.",
                   "f1": "جستجو و فیلتر هوشمند موقعیت‌محور", "f2": "چت درون‌برنامه و مدیریت ارتباطات",
                   "f3": "حساب‌های تأییدشده و فرایند انتشار امن", "f4": "آگهی ویژه، برجسته‌سازی و عضویت در سرویس",
                   "f5": "پنل مدیریت محتوا و آنالیتیکس"},
            "ar": {"subtitle": "تطبيقات إعلانات وقوائم مع محادثة وبحث وفلاتر ونشر آمن.",
                   "p1": "من إعلانات السيارات والعقارات إلى لوحات الوظائف وأسواق السلع المستعملة، نبني تطبيقات الإعلانات المُبوبة التي تُبقي المشترين والبائعين نشطين. الحسابات الموثقة والمحادثة داخل التطبيق والبحث حسب الموقع كلها مدمجة.",
                   "p2": "جاهز للإيرادات مع إعلانات مميزة وترقيات وعضويات ممتازة، مصمم للثقة والتفاعل العالي.",
                   "f1": "بحث وفلاتر ذكية حسب الموقع", "f2": "محادثة داخل التطبيق وإدارة جهات الاتصال",
                   "f3": "حسابات موثقة ونشر آمن", "f4": "إعلانات مميزة وترقيات وعضويات",
                   "f5": "لوحة إشراف وتحليلات"},
        },
    },
    {
        "cat": "apps", "file": "book-reader-app.html", "img": "books",
        "title_key": "services.apps.reader", "title_en": "Book Reader App",
        "desc": "E-book and audiobook reader apps by AmatisBerry — synced libraries, subscriptions and a beautiful reading experience.",
        "c": {
            "en": {"subtitle": "Book reader apps for ebooks and audiobooks with synced libraries and subscriptions.",
                   "p1": "A great reading app is about focus. We craft calm, typographic-first experiences with adjustable fonts, themes, offline downloads and cross-device syncing of your library.",
                   "p2": "Support subscriptions, rentals, gifting and seamless payment integration to turn readers into a recurring audience.",
                   "f1": "Beautiful typography & reading themes", "f2": "Offline downloads & library sync",
                   "f3": "Audiobook playback & bookmarks", "f4": "Subscriptions, rentals & gifting",
                   "f5": "Progress tracking across devices"},
            "de": {"subtitle": "Lese-Apps für E-Books und Hörbücher mit synchronisierten Bibliotheken und Abonnements.",
                   "p1": "Eine großartige Lese-App dreht sich um Konzentration. Wir gestalten ruhige, typografie-orientierte Erlebnisse mit anpassbaren Schriftarten, Themes, Offline-Downloads und geräteübergreifender Synchronisierung Ihrer Bibliothek.",
                   "p2": "Unterstützen Sie Abonnements, Verleih, Verschenken und nahtlose Zahlungsintegration, um aus Lesern ein wiederkehrendes Publikum zu machen.",
                   "f1": "Schöne Typografie & Lesethemen", "f2": "Offline-Downloads & Bibliotheks-Sync",
                   "f3": "Hörbuch-Playback & Lesezeichen", "f4": "Abonnements, Verleih & Verschenken",
                   "f5": "Fortschritts-Tracking über Geräte hinweg"},
            "fa": {"subtitle": "اپلیکیشن کتاب‌خوان برای کتاب الکترونیک و صوتی با کتابخانه همگام و اشتراک.",
                   "p1": "یک اپلیکیشن کتاب‌خوان خوب حول محور تمرکز ساخته می‌شود. تجربه‌هایی آرام و مبتنی بر تایپوگرافی طراحی می‌کنیم با فونت‌ها و تم‌های قابل تنظیم، دانلود آفلاین و همگام‌سازی کتابخانه بین دستگاه‌ها.",
                   "p2": "اشتراک، اجاره، هدیه دادن کتاب و پرداخت یکپارچه را پشتیبانی می‌کنیم تا خواننده‌ها به مخاطب دائمی تبدیل شوند.",
                   "f1": "تایپوگرافی زیبا و تم‌های مطالعه", "f2": "دانلود آفلاین و همگام‌سازی کتابخانه",
                   "f3": "پخش کتاب صوتی و نشانه‌گذاری", "f4": "اشتراک، اجاره و هدیه کتاب",
                   "f5": "پیگیری پیشرفت مطالعه بین دستگاه‌ها"},
            "ar": {"subtitle": "تطبيقات قراءة للكتب الإلكترونية والصوتية مع مكتبات متزامنة واشتراكات.",
                   "p1": "تطبيق القراءة العظيم يعتمد على التركيز. نصمم تجارب هادئة قائمة على الطباعة مع خطوط وسمات قابلة للضبط وتحميل دون اتصال ومزامنة مكتبتك بين الأجهزة.",
                   "p2": "ندعم الاشتراكات والاستعارة والهدايا وتكامل الدفع السلس لتحويل القراء إلى جمهور متكرر.",
                   "f1": "طباعة جميلة وسمات قراءة", "f2": "تحميل دون اتصال ومزامنة المكتبة",
                   "f3": "تشغيل الكتب الصوتية والعلامات المرجعية", "f4": "اشتراكات واستعارة وهدايا",
                   "f5": "تتبع التقدم عبر الأجهزة"},
        },
    },
    {
        "cat": "apps", "file": "tourism-app.html", "img": "travel",
        "title_key": "services.apps.tourism", "title_en": "Tourism App",
        "desc": "Travel and tourism apps by AmatisBerry — tours, itineraries, maps and unforgettable local experiences.",
        "c": {
            "en": {"subtitle": "Tourism and travel apps with tours, itineraries, maps and local experiences.",
                   "p1": "We help tourism businesses reach travelers with beautiful apps for tours, hotels, flights and experiences. Interactive maps, offline guides and multi-language content make every trip smoother.",
                   "p2": "Include reviews, wishlists, secure booking and payment to turn inspiration into confirmed trips.",
                   "f1": "Tours, itineraries & experiences", "f2": "Interactive maps & offline guides",
                   "f3": "Multi-language traveler content", "f4": "Secure booking & payments",
                   "f5": "Reviews, wishlists & tailored offers"},
            "de": {"subtitle": "Tourismus- und Reise-Apps mit Touren, Reiserouten, Karten und lokalen Erlebnissen.",
                   "p1": "Wir helfen Tourismusunternehmen, Reisende mit schönen Apps für Touren, Hotels, Flüge und Erlebnisse zu erreichen. Interaktive Karten, Offline-Reiseführer und mehrsprachige Inhalte machen jede Reise einfacher.",
                   "p2": "Mit Bewertungen, Wunschlisten, sicherer Buchung und Zahlung entwickeln Sie aus Inspiration bestätigte Reisen.",
                   "f1": "Touren, Routen & Erlebnisse", "f2": "Interaktive Karten & Offline-Guides",
                   "f3": "Mehrsprachige Inhalte für Reisende", "f4": "Sichere Buchung & Zahlung",
                   "f5": "Bewertungen, Wunschlisten & Angebote"},
            "fa": {"subtitle": "اپلیکیشن‌های گردشگری و سفر با تور، سفرنامه، نقشه و تجربه‌های محلی.",
                   "p1": "به کسب‌وکارهای گردشگری کمک می‌کنیم با اپلیکیشن‌های زیبا برای تور، هتل، پرواز و تجربه‌های محلی به مسافران برسند. نقشه‌های تعاملی، راهنمای آفلاین و محتوای چندزبانه هر سفر را روان‌تر می‌کند.",
                   "p2": "نظرات، علاقه‌مندی، رزرو امن و پرداخت را اضافه می‌کنیم تا الهام به سفر قطعی تبدیل شود.",
                   "f1": "تور، سفرنامه و تجربه‌های محلی", "f2": "نقشه تعاملی و راهنمای آفلاین",
                   "f3": "محتوای چندزبانه برای مسافران", "f4": "رزرو و پرداخت امن",
                   "f5": "نظرات، علاقه‌مندی و پیشنهادهای ویژه"},
            "ar": {"subtitle": "تطبيقات السياحة والسفر مع جولات ومسارات وخرائط وتجارب محلية.",
                   "p1": "نساعد شركات السياحة على الوصول للمسافرين بتطبيقات جميلة للجولات والفنادق والرحلات والتجارب. الخرائط التفاعلية والأدلة دون اتصال والمحتوى متعدد اللغات تجعل كل رحلة أسهل.",
                   "p2": "نضيف التقييمات وقوائم الأمنيات والحجز الآمن والدفع لتحويل الإلهام إلى رحلات مؤكدة.",
                   "f1": "جولات ومسارات وتجارب محلية", "f2": "خرائط تفاعلية وأدلة دون اتصال",
                   "f3": "محتوى متعدد اللغات للمسافرين", "f4": "حجز ودفع آمن",
                   "f5": "تقييمات وقوائم أمنيات وعروض مخصصة"},
        },
    },
    {
        "cat": "apps", "file": "taxi-app.html", "img": "taxi",
        "title_key": "services.apps.taxi", "title_en": "Taxi Booking App",
        "desc": "Ride-hailing apps by AmatisBerry — live driver tracking, smart dispatch and in-app payments.",
        "c": {
            "en": {"subtitle": "Ride-hailing apps with live tracking, driver dispatch and in-app payments.",
                   "p1": "We build complete taxi and ride-hailing platforms for cities and fleets. Rider and driver apps, live GPS tracking, fare estimation and smart dispatch work together for a smooth experience.",
                   "p2": "Add peaks/fare pricing, driver ratings, trip history and multi-currency payments to run operations efficiently.",
                   "f1": "Rider & driver mobile apps", "f2": "Live GPS tracking & ETA",
                   "f3": "Smart automatic driver dispatch", "f4": "Fare estimation & surge pricing",
                   "f5": "Ratings, history & multi-currency payments"},
            "de": {"subtitle": "Ride-Hailing-Apps mit Live-Tracking, Fahrer-Dispatch und In-App-Zahlungen.",
                   "p1": "Wir entwickeln komplette Taxi- und Ride-Hailing-Plattformen für Städte und Flotten. Fahrgast- und Fahrer-Apps, Live-GPS-Tracking, Fahrpreisberechnung und smarter Dispatch arbeiten für ein reibungsloses Erlebnis zusammen.",
                   "p2": "Höherpreisphasen, Fahrerbewertungen, Fahrtverlauf und Zahlungen in mehreren Währungen machen Ihren Betrieb effizient.",
                   "f1": "Fahrgast- & Fahrer-Apps", "f2": "Live-GPS-Tracking & ETA",
                   "f3": "Smarter automatischer Fahrer-Dispatch", "f4": "Fahrpreisberechnung & dynamische Preise",
                   "f5": "Bewertungen, Verlauf & Multiwährungs-Zahlungen"},
            "fa": {"subtitle": "اپلیکیشن‌های تاکسی اینترنتی با رهگیری زنده، اعزام هوشمند و پرداخت درون‌برنامه.",
                   "p1": "پلتفرم‌های کامل تاکسی و سرویس حمل‌ونقل برای شهرها و ناوگان‌ها می‌سازیم. اپلیکیشن مسافر و راننده، رهگیری زنده GPS، تخمین کرایه و اعزام هوشمند با هم تجربه‌ای روان را رقم می‌زنند.",
                   "p2": "نرخ‌گذاری پیک، امتیازدهی به راننده، تاریخچه سفرها و پرداخت چندارزی را اضافه می‌کنیم تا عملیات شما بهینه باشد.",
                   "f1": "اپلیکیشن مسافر و راننده", "f2": "رهگیری زنده GPS و زمان رسیدن",
                   "f3": "اعزام هوشمند و خودکار راننده", "f4": "تخمین کرایه و قیمت‌گذاری پیک",
                   "f5": "امتیازدهی، تاریخچه و پرداخت چندارزی"},
            "ar": {"subtitle": "تطبيقات طلب سيارات أجرة مع تتبع مباشر وإرسال ذكي ومدفوعات داخل التطبيق.",
                   "p1": "نبني منصات كاملة لسيارات الأجرة والتوصيل للمدن وأساطيل المركبات. تطبيقات الراكب والسائق وتتبع GPS المباشر وتقدير الأجرة والإرسال الذكي تعمل معًا لتجربة سلسة.",
                   "p2": "نضيف تسعير فترات الذروة وتقييمات السائقين وسجل الرحلات ومدفوعات متعددة العملات لإدارة فعالة.",
                   "f1": "تطبيقات الراكب والسائق", "f2": "تتبع GPS مباشر ووقت الوصول المتوقع",
                   "f3": "إرسال ذكي وتلقائي للسائقين", "f4": "تقدير الأجرة وتسعير الذروة",
                   "f5": "تقييمات وسجل ومدفوعات متعددة العملات"},
        },
    },
    {
        "cat": "apps", "file": "flight-hotel-app.html", "img": "hotel",
        "title_key": "services.apps.booking", "title_en": "Flight & Hotel Booking",
        "desc": "Flight and hotel booking apps by AmatisBerry — real-time availability, pricing and instant confirmation.",
        "c": {
            "en": {"subtitle": "Booking apps with availability, pricing and instant confirmation.",
                   "p1": "We build booking platforms for flights, hotels and travel packages. Search across providers, compare prices in real time and confirm reservations instantly with a smooth, secure flow.",
                   "p2": "Integrate provider APIs, manage capacity and availability per property, and keep users updated with booking emails and app notifications.",
                   "f1": "Flights, hotels & packages search", "f2": "Real-time prices & availability",
                   "f3": "Instant confirmation & e-tickets", "f4": "Provider API integrations",
                   "f5": "Booking emails & app notifications"},
            "de": {"subtitle": "Buchungs-Apps mit Verfügbarkeit, Preisen und sofortiger Bestätigung.",
                   "p1": "Wir entwickeln Buchungsplattformen für Flüge, Hotels und Reisepakete. Suche über Anbieter hinweg, Preisvergleich in Echtzeit und sofortige Bestätigung in einem sicheren, reibungslosen Ablauf.",
                   "p2": "Integrieren Sie Anbieter-APIs, verwalten Sie Kapazitäten und Verfügbarkeiten pro Unterkunft und informieren Sie Nutzer per Buchungs-E-Mail und Hinweis.",
                   "f1": "Flüge, Hotels & Paketsuche", "f2": "Echtzeit-Preise & Verfügbarkeit",
                   "f3": "Sofortige Bestätigung & E-Tickets", "f4": "Anbieter-API-Integrationen",
                   "f5": "Buchungs-E-Mails & App-Hinweise"},
            "fa": {"subtitle": "اپلیکیشن رزرو با نمایش موجودی، قیمت و تأیید فوری.",
                   "p1": "پلتفرم‌های رزرو پرواز، هتل و پکیج سفر می‌سازیم. جستجو بین ارائه‌دهندگان، مقایسه قیمت به‌صورت زنده و تأیید فوری رزرو در یک فرایند امن و روان.",
                   "p2": "API ارائه‌دهندگان را یکپارچه می‌کنیم، ظرفیت و موجودی هر ملک را مدیریت می‌کنیم و با ایمیل و نوتیفیکیشن کاربر را به‌روز نگه می‌داریم.",
                   "f1": "جستجوی پرواز، هتل و پکیج", "f2": "قیمت و موجودی لحظه‌ای",
                   "f3": "تأیید فوری و بلیت الکترونیک", "f4": "یکپارچه‌سازی API ارائه‌دهندگان",
                   "f5": "ایمیل رزرو و نوتیفیکیشن اپلیکیشن"},
            "ar": {"subtitle": "تطبيقات حجز مع توفر وفترات وأسعار وتأكيد فوري.",
                   "p1": "نبني منصات حجز للرحلات الجوية والفنادق وباقات السفر. البحث عبر مقدمي الخدمات ومقارنة الأسعار لحظيًا وتأكيد الحجوزات فورًا في تدفق آمن وسلس.",
                   "p2": "ندمج واجهات برمجة مقدمي الخدمات وندير السعة والتوفر لكل منشأة ونبقي المستخدمين على اطلاع بالبريد وإشعارات التطبيق.",
                   "f1": "بحث الرحلات والفنادق والباقات", "f2": "أسعار وتوفر لحظي",
                   "f3": "تأكيد فوري وتذاكر إلكترونية", "f4": "تكامل مع واجهات برمجة المزودين",
                   "f5": "بريد الحجز وإشعارات التطبيق"},
        },
    },
]